import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { SeededRng } from "../src/core/rng.js";
import { BattleSystem, isScenarioObjectiveOverdue, makeEnemy, makeNpcCompanion, makePlayerCombatant } from "../src/systems/battle-system.js";
import { packBattle, restoreBattle } from "../src/persistence/battle-snapshot.js";

const read=name=>JSON.parse(fs.readFileSync(new URL(`../src/data/${name}.json`,import.meta.url),"utf8")).data;const skills=read("skills"),enemies=read("enemies");
const baseCharacter={id:"hero",name:"測試俠客",stats:{strength:25,constitution:25,agility:20,comprehension:15,willpower:15},equippedSkills:["skill_001"],maxHp:225,maxPosture:100,maxInner:50};
test("completed scenario objectives are never reported overdue",()=>{const goal={done:2,objectives:["護住車夫","攔截逃者"],limit:4};assert.equal(isScenarioObjectiveOverdue(goal,2),false);assert.equal(isScenarioObjectiveOverdue(goal,5),false);assert.equal(isScenarioObjectiveOverdue({...goal,done:1},4),false);assert.equal(isScenarioObjectiveOverdue({...goal,done:1},5),true);assert.equal(isScenarioObjectiveOverdue({...goal,limit:Infinity,done:0},50),false);});
test("battle resolves deterministically and never creates negative resources",()=>{const rng=new SeededRng("battle-regression");const battle=new BattleSystem({party:[makePlayerCombatant(baseCharacter,skills),makeNpcCompanion("陸小川",skills)],enemies:[makeEnemy(enemies[0],skills,2)],rng});for(let turn=0;turn<60&&!battle.finished;turn++){const target=battle.living("enemy")[0];battle.submit({type:"skill",skillId:"skill_001",targetId:target.id});for(const actor of battle.all){assert.ok(actor.hp>=0);assert.ok(actor.posture>=0);assert.ok(actor.inner>=0);}}assert.ok(["victory","defeat"].includes(battle.finished));});
test("posture break persists through the following round then restores",()=>{const rng=new SeededRng("posture");const enemy=makeEnemy(enemies[0],skills,2);enemy.maxHp=9999;enemy.hp=9999;enemy.posture=1;const battle=new BattleSystem({party:[makePlayerCombatant(baseCharacter,skills),makeNpcCompanion("陸小川",skills)],enemies:[enemy],rng});battle.submit({type:"attack",targetId:enemy.id});assert.equal(enemy.vulnerableTurns,1,"vulnerability remains for the next round");battle.submit({type:"defend"});assert.ok(enemy.posture>0,"posture restores after the vulnerable round resolves");assert.equal(enemy.vulnerableTurns,0);});
test("skill realm applies five percent power and three percent cost per level",()=>{const original=skills.find(skill=>skill.id==="skill_001");const hero=makePlayerCombatant({...baseCharacter,skills:{skill_001:{realm:4,proficiency:0,completeness:1}}},skills);const mastered=hero.skills[0];assert.equal(mastered.power.hp,Math.round(original.power.hp*1.2));assert.equal(mastered.power.posture,Math.round(original.power.posture*1.2));assert.equal(mastered.innerCost,Math.round(original.innerCost*.88));});
test("defense skills use their published reduction instead of a fixed value",()=>{const defenseSkill=skills.find(skill=>skill.type==="defense"&&skill.effects.some(effect=>effect.effectId==="defend"));const hero=makePlayerCombatant({...baseCharacter,equippedSkills:[defenseSkill.id],skills:{[defenseSkill.id]:{realm:0,completeness:1}}},skills);const battle=new BattleSystem({party:[hero],enemies:[makeEnemy(enemies[0],skills,1)],rng:new SeededRng("defense-params")});battle.resolve(hero,{type:"skill",skillId:defenseSkill.id});const effect=defenseSkill.effects.find(item=>item.effectId==="defend");assert.equal(hero.defenseHpReduction,effect.params.hpReduction);assert.equal(hero.defensePostureReduction,effect.params.postureReduction);});
test("control skill status enters the target lifecycle",()=>{const control=skills.find(skill=>skill.type==="control"&&skill.effects.some(effect=>effect.effectId==="status"));const hero=makePlayerCombatant({...baseCharacter,equippedSkills:[control.id],skills:{[control.id]:{realm:0,completeness:1}}},skills);const enemy=makeEnemy(enemies[0],skills,1);const battle=new BattleSystem({party:[hero],enemies:[enemy],rng:new SeededRng("status")});battle.resolve(hero,{type:"skill",skillId:control.id,targetId:enemy.id});assert.ok(enemy.statuses.length>0);assert.match(enemy.statuses[0].description,/內力消耗|速度|防禦|攻擊|架勢/);});
test("support healing restores the selected ally without hitting them or overshooting maximum HP",()=>{const skill=skills.find(s=>s.effects.some(effect=>effect.effectId==='heal_pct'));const hero=makePlayerCombatant({...baseCharacter,equippedSkills:[skill.id]},skills);const ally=makeNpcCompanion('陸小川',skills);const enemy=makeEnemy(enemies[0],skills,1);const battle=new BattleSystem({party:[hero,ally],enemies:[enemy],rng:new SeededRng('support-heal')});ally.hp=ally.maxHp-40;const initialInner=hero.inner;battle.resolve(hero,{type:'skill',skillId:skill.id,targetId:enemy.id});assert.equal(hero.inner,initialInner);assert.equal(battle.lastActionResults.at(-1).executed,false);battle.resolve(hero,{type:'skill',skillId:skill.id,targetId:ally.id});assert.equal(ally.hp,ally.maxHp);assert.equal(enemy.hp,enemy.maxHp);assert.equal(hero.inner,initialInner-skill.innerCost);assert.equal(battle.events.at(-1).type,'heal');hero.inner=0;ally.hp-=20;battle.resolve(hero,{type:'skill',skillId:skill.id,targetId:ally.id});assert.equal(ally.hp,ally.maxHp-20);assert.ok(enemy.hp<enemy.maxHp);});
test("team buffs increase damage, refresh without stacking and survive battle reload",()=>{const skill=skills.find(s=>s.effects.some(effect=>effect.effectId==='battle_buff'&&effect.params.stat==='damage'));const hero=makePlayerCombatant({...baseCharacter,equippedSkills:[skill.id]},skills);const ally=makeNpcCompanion('陸小川',skills);const enemy=makeEnemy(enemies[0],skills,1);enemy.hp=enemy.maxHp=9999;const battle=new BattleSystem({party:[hero,ally],enemies:[enemy],rng:new SeededRng('buff-hit')});battle.resolve(hero,{type:'skill',skillId:skill.id,targetId:hero.id});assert.equal(hero.buffs.length,1);assert.deepEqual(hero.buffs,ally.buffs);battle.resolve(hero,{type:'skill',skillId:skill.id,targetId:hero.id});assert.equal(hero.buffs.length,1);const restored=restoreBattle(packBattle(battle,{kind:'test'})).battle;assert.deepEqual(restored.party[0].buffs,hero.buffs);const unbuffed=makeNpcCompanion('陸小川',skills),plainEnemy=makeEnemy(enemies[0],skills,1);plainEnemy.hp=plainEnemy.maxHp=9999;const plain=new BattleSystem({party:[unbuffed],enemies:[plainEnemy],rng:new SeededRng('buff-hit')});battle.attack(ally,enemy,null);plain.attack(unbuffed,plainEnemy,null);assert.ok(9999-enemy.hp>9999-plainEnemy.hp);for(let i=0;i<3;i++)battle.endRound();assert.equal(ally.buffs.length,0);});
test("a medical companion learns healing support and uses it on a wounded teammate",()=>{const medic=makeNpcCompanion({id:'npc_002',name:'沈青禾',role:'控制／醫療'},skills);const hero=makePlayerCombatant(baseCharacter,skills),enemy=makeEnemy(enemies[0],skills,1);const battle=new BattleSystem({party:[hero,medic],enemies:[enemy],rng:new SeededRng('medic-ai')});hero.hp=Math.round(hero.maxHp*.4);const action=battle.chooseAllyAction(medic);assert.equal(action.targetId,hero.id);assert.ok(medic.skills.find(skill=>skill.id===action.skillId)?.effects.some(effect=>effect.effectId==='heal_pct'));battle.resolve(medic,action);assert.ok(hero.hp>hero.maxHp*.4);});
