import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { SeededRng } from "../src/core/rng.js";
import { BattleSystem, isScenarioObjectiveOverdue, makeEnemy, makeNpcCompanion, makePlayerCombatant } from "../src/systems/battle-system.js";

const read=name=>JSON.parse(fs.readFileSync(new URL(`../src/data/${name}.json`,import.meta.url),"utf8")).data;const skills=read("skills"),enemies=read("enemies");
const baseCharacter={id:"hero",name:"測試俠客",stats:{strength:25,constitution:25,agility:20,comprehension:15,willpower:15},equippedSkills:["skill_001"],maxHp:225,maxPosture:100,maxInner:50};
test("completed scenario objectives are never reported overdue",()=>{const goal={done:2,objectives:["護住車夫","攔截逃者"],limit:4};assert.equal(isScenarioObjectiveOverdue(goal,2),false);assert.equal(isScenarioObjectiveOverdue(goal,5),false);assert.equal(isScenarioObjectiveOverdue({...goal,done:1},4),false);assert.equal(isScenarioObjectiveOverdue({...goal,done:1},5),true);assert.equal(isScenarioObjectiveOverdue({...goal,limit:Infinity,done:0},50),false);});
test("battle resolves deterministically and never creates negative resources",()=>{const rng=new SeededRng("battle-regression");const battle=new BattleSystem({party:[makePlayerCombatant(baseCharacter,skills),makeNpcCompanion("陸小川",skills)],enemies:[makeEnemy(enemies[0],skills,2)],rng});for(let turn=0;turn<60&&!battle.finished;turn++){const target=battle.living("enemy")[0];battle.submit({type:"skill",skillId:"skill_001",targetId:target.id});for(const actor of battle.all){assert.ok(actor.hp>=0);assert.ok(actor.posture>=0);assert.ok(actor.inner>=0);}}assert.ok(["victory","defeat"].includes(battle.finished));});
test("posture break persists through the following round then restores",()=>{const rng=new SeededRng("posture");const enemy=makeEnemy(enemies[0],skills,2);enemy.maxHp=9999;enemy.hp=9999;enemy.posture=1;const battle=new BattleSystem({party:[makePlayerCombatant(baseCharacter,skills),makeNpcCompanion("陸小川",skills)],enemies:[enemy],rng});battle.submit({type:"attack",targetId:enemy.id});assert.equal(enemy.vulnerableTurns,1,"vulnerability remains for the next round");battle.submit({type:"defend"});assert.ok(enemy.posture>0,"posture restores after the vulnerable round resolves");assert.equal(enemy.vulnerableTurns,0);});
test("skill realm applies five percent power and three percent cost per level",()=>{const original=skills.find(skill=>skill.id==="skill_001");const hero=makePlayerCombatant({...baseCharacter,skills:{skill_001:{realm:4,proficiency:0,completeness:1}}},skills);const mastered=hero.skills[0];assert.equal(mastered.power.hp,Math.round(original.power.hp*1.2));assert.equal(mastered.power.posture,Math.round(original.power.posture*1.2));assert.equal(mastered.innerCost,Math.round(original.innerCost*.88));});
test("defense skills use their published reduction instead of a fixed value",()=>{const defenseSkill=skills.find(skill=>skill.type==="defense"&&skill.effects.some(effect=>effect.effectId==="defend"));const hero=makePlayerCombatant({...baseCharacter,equippedSkills:[defenseSkill.id],skills:{[defenseSkill.id]:{realm:0,completeness:1}}},skills);const battle=new BattleSystem({party:[hero],enemies:[makeEnemy(enemies[0],skills,1)],rng:new SeededRng("defense-params")});battle.resolve(hero,{type:"skill",skillId:defenseSkill.id});const effect=defenseSkill.effects.find(item=>item.effectId==="defend");assert.equal(hero.defenseHpReduction,effect.params.hpReduction);assert.equal(hero.defensePostureReduction,effect.params.postureReduction);});
test("control skill status enters the target lifecycle",()=>{const control=skills.find(skill=>skill.type==="control"&&skill.effects.some(effect=>effect.effectId==="status"));const hero=makePlayerCombatant({...baseCharacter,equippedSkills:[control.id],skills:{[control.id]:{realm:0,completeness:1}}},skills);const enemy=makeEnemy(enemies[0],skills,1);const battle=new BattleSystem({party:[hero],enemies:[enemy],rng:new SeededRng("status")});battle.resolve(hero,{type:"skill",skillId:control.id,targetId:enemy.id});assert.ok(enemy.statuses.length>0);assert.match(enemy.statuses[0].description,/內力消耗|速度|防禦|攻擊|架勢/);});
test("basic guard command is rejected while guard skills protect allies without friendly-fire fallbacks",()=>{const guardSkill=skills.find(skill=>skill.type==="guard"&&skill.effects.some(effect=>effect.effectId==="guard"));assert.ok(guardSkill);const hero=makePlayerCombatant({...baseCharacter,equippedSkills:[guardSkill.id],skills:{[guardSkill.id]:{realm:0,completeness:1}}},skills);const ally=makeNpcCompanion("陸小川",skills);const enemy=makeEnemy(enemies[0],skills,1);const battle=new BattleSystem({party:[hero,ally],enemies:[enemy],rng:new SeededRng("guard-removal")});const startingInner=hero.inner;battle.resolve(hero,{type:"guard",targetId:ally.id});assert.equal(hero.guard,null);assert.equal(battle.lastActionResults.at(-1).executed,false);battle.resolve(hero,{type:"skill",skillId:guardSkill.id,targetId:enemy.id});assert.equal(hero.guard,null);assert.equal(hero.inner,startingInner,"an invalid enemy target does not charge inner");assert.equal(battle.lastActionResults.at(-1).executed,false);battle.resolve(hero,{type:"skill",skillId:guardSkill.id,targetId:ally.id});assert.deepEqual(hero.guard,{targetId:ally.id,hits:1,reduction:guardSkill.effects.find(effect=>effect.effectId==="guard").params.reduction});const allyHp=ally.hp;enemy.stats.strength=100;battle.attack(enemy,ally,null);assert.equal(ally.hp,allyHp,"guard skill redirects the hit away from the selected ally");assert.ok(hero.hp<hero.maxHp,"the guard absorbs the redirected attack");const enemyHp=enemy.hp;hero.inner=0;battle.resolve(hero,{type:"skill",skillId:guardSkill.id,targetId:ally.id});assert.equal(ally.hp,allyHp,"an underfunded guard skill must never fall back to attacking its ally");assert.ok(enemy.hp<enemyHp,"underfunded guard skills fall back to attacking the enemy");});
