import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { SeededRng } from "../src/core/rng.js";
import { adjustStatAllocation, createCharacter, rollStartingTalents } from "../src/systems/progression-system.js";
import { DEFAULT_STATS, STAT_DESCRIPTIONS, STAT_LABELS } from "../src/config/constants.js";

const read=name=>JSON.parse(fs.readFileSync(new URL(`../src/data/${name}.json`,import.meta.url),"utf8")).data;
const talents=read("talents"),skills=read("skills");
test("starting talent roll offers three positives and at most one pure negative",()=>{for(let i=0;i<200;i++){const roll=rollStartingTalents(talents,new SeededRng(`talent-${i}`));assert.equal(roll.choice.length,3);assert.ok(roll.choice.every(t=>t.type==="positive"));assert.equal(new Set([...roll.choice,...roll.random].map(t=>t.id)).size,5);assert.ok(roll.random.filter(t=>t.type==="negative").length<=1);}});
test("character creation enforces 100 stat points",()=>{const roll=rollStartingTalents(talents,new SeededRng("create"));const character=createCharacter({name:"林青雲",gender:"unspecified",identityId:"identity_constable",stats:{strength:20,constitution:20,agility:20,comprehension:20,willpower:20},startSkillName:"衙門刀法"},[roll.choice[0],...roll.random],skills);assert.equal(Object.values(character.stats).reduce((a,b)=>a+b,0),100);assert.equal(character.equippedSkills.length,1);});
test("stat allocation cannot go above 100 and supports safe point transfer",()=>{assert.equal(adjustStatAllocation(DEFAULT_STATS,"strength",1),null);const reduced=adjustStatAllocation(DEFAULT_STATS,"constitution",-1);assert.equal(Object.values(reduced).reduce((a,b)=>a+b,0),99);const transferred=adjustStatAllocation(reduced,"strength",1);assert.equal(transferred.strength,21);assert.equal(transferred.constitution,19);assert.equal(Object.values(transferred).reduce((a,b)=>a+b,0),100);assert.equal(adjustStatAllocation(transferred,"strength",1),null);assert.equal(adjustStatAllocation(transferred,"missing",1),null);assert.equal(adjustStatAllocation(transferred,"strength",2),null);assert.deepEqual(DEFAULT_STATS,{strength:20,constitution:20,agility:20,comprehension:20,willpower:20});});
test("all five creation stats have a visible explanation matching the supported effects",()=>{for(const key of Object.keys(DEFAULT_STATS)){assert.ok(STAT_LABELS[key],`missing label ${key}`);assert.ok(STAT_DESCRIPTIONS[key],`missing explanation ${key}`);}assert.match(STAT_DESCRIPTIONS.strength,/傷害/);assert.match(STAT_DESCRIPTIONS.constitution,/5 氣血上限、2 架勢上限/);assert.match(STAT_DESCRIPTIONS.comprehension,/熟練度/);assert.match(STAT_DESCRIPTIONS.willpower,/尚未接入/);});
test("invalid stat allocation is rejected",()=>{const roll=rollStartingTalents(talents,new SeededRng("bad"));assert.throws(()=>createCharacter({name:"錯誤",gender:"unspecified",identityId:"identity_constable",stats:{strength:50,constitution:50,agility:20,comprehension:20,willpower:20},startSkillName:"衙門刀法"},[roll.choice[0],...roll.random],skills),/合計/);});
