import test from 'node:test';
import assert from 'node:assert/strict';
import { createWorld, GameEngine } from '../src/core/game-engine.js';
import { createZhaoyeState, endingFor, recordLoss } from '../src/core/zhaoye-engine.js';
import { ZHAOYE_ORDER, ZHAOYE_SCENES, BATTLES } from '../src/core/zhaoye-story.js';
import { ZHAOYE_SCRIPT } from '../src/data/zhaoye-script.js';

function fresh(){const world=createWorld({name:'照夜行測試',startingCountry:'dasheng',ownerCharacterId:'hero',seed:'zhaoye'});world.zhaoye=createZhaoyeState();world.currentSceneId='1-0';const character={id:'hero',moneyWen:1000};return {world,character,engine:new GameEngine({world,character,content:{}})};}
function walk({variant=0,defeat=false,skip=false,poor=false}={}){let {world,character,engine}=fresh();if(poor)character.moneyWen=0;let steps=0,chapters=0;while(!world.flags.game_complete||world.zhaoye.aftermath){assert.ok(++steps<1000,'No narrative deadlocks');const view=engine.sceneView();const id=world.currentSceneId;let options=view.choices.filter(c=>!c.disabled);let choice=options.find(c=>c.id==='continue'||c.id==='operate'||c.id==='conclude')??options.find(c=>c.id.startsWith('fulfil:'))??options.find(c=>c.id==='next-chapter');if(!choice)choice=skip&&options.find(c=>c.id==='skip')||options[variant%options.length];assert.ok(choice,`No choice in ${id}`);const result=engine.choose(choice.id);if(result.complete)chapters++;
 if(result.battle){const objectives=engine.battleProgress().objectives;if(!defeat)for(let i=0;i<objectives.length;i++)engine.battleAction('objective',i+1);engine.finishBattle(result,defeat?'defeat':'victory');}
 assert.ok(character.moneyWen>=0);assert.equal(new Set(world.zhaoye.losses).size,world.zhaoye.losses.length);
 // Simulate a reload on every choice; no closures may carry essential state.
 world=structuredClone(world);character=structuredClone(character);engine=new GameEngine({world,character,content:{}});
 }return {world,character,engine,steps,chapters};}

test('new script has 102 ordered scenes, all 64 supplemental events and three authored options each',()=>{assert.equal(ZHAOYE_ORDER.length,102);assert.equal(new Set(ZHAOYE_ORDER).size,102);const extra=ZHAOYE_SCRIPT.filter(s=>/[A-D]$/.test(s.id));assert.equal(extra.length,64);for(const s of extra)assert.equal(s.options.length,3,s.id);for(const id of ZHAOYE_ORDER)assert.ok(ZHAOYE_SCENES[id].choices.length,id);});
test('new campaign survives reload at every step, optional skips, poverty and all battle defeats',()=>{for(const variant of [0,1,2])for(const defeat of [false,true])for(const skip of [false,true]){const {world,chapters}=walk({variant,defeat,skip,poor:true});assert.equal(chapters,8);assert.equal(world.zhaoye.custody.gu,'detained');assert.equal(world.zhaoye.custody.wei,'detained');assert.equal(world.zhaoye.zouAlive,true);assert.equal(world.zhaoye.rewards.length,8);}});
test('investigations do not force an exclusive branch or award duplicate progress',()=>{const {world,engine}=fresh();world.currentSceneId='1-1';engine.choose('A');engine.choose('continue');assert.equal(world.currentSceneId,'1-1');assert.throws(()=>engine.choose('A'));engine.choose('B');engine.choose('continue');assert.ok(!engine.sceneView().choices.some(c=>c.id==='conclude'));engine.choose('C');engine.choose('continue');engine.choose('conclude');assert.equal(world.currentSceneId,'1-1A');});
test('chapter seven preparation budget is explicit and cannot be exceeded',()=>{for(const limit of [2,3]){const {world,engine}=fresh();world.chapter=7;world.currentSceneId='7-1';world.zhaoye.preparationLimit=limit;for(const key of 'ABC'.slice(0,limit)){engine.choose(key);engine.choose('continue');}assert.deepEqual(engine.sceneView().choices.map(c=>c.id),['conclude']);assert.equal(world.zhaoye.preparations.length,limit);}});
test('promise is pending until an actual safe-point return, and cannot be fulfilled twice',()=>{const {world,engine}=fresh();world.chapter=4;world.currentSceneId='4-1A';engine.choose('C');assert.equal(world.zhaoye.promises['4-1A'].status,'pending');engine.choose('continue');world.zhaoye.chapterSafe=true;engine.choose('fulfil:4-1A');assert.equal(world.zhaoye.promises['4-1A'].status,'fulfilled');engine.choose('continue');assert.throws(()=>engine.choose('fulfil:4-1A'));});
test('Tao loss and final lock progress are persistent and idempotent',()=>{const {world,engine}=fresh();world.currentSceneId='1-3';const battle=engine.choose('A');engine.finishBattle(battle,'defeat');assert.equal(world.zhaoye.taoAlive,false);recordLoss(world,'mill');assert.deepEqual(world.zhaoye.losses,['mill']);engine.choose('continue');world.chapter=8;world.currentSceneId='8-4';const final=engine.choose('A');engine.battleAction('objective',1);engine.finishBattle(final,'defeat');assert.equal(world.zhaoye.facilities.mainLock,1);engine.choose('continue');engine.finishBattle(engine.choose('A'),'defeat');assert.equal(world.zhaoye.facilities.mainLock,2);assert.equal(world.zhaoye.custody.gu,'detained');assert.ok(world.zhaoye.losses.includes('forced_gate'));});
test('endings require verified evidence, old-case accountability and the specified support types',()=>{const {world}=fresh(),s=world.zhaoye;assert.equal(endingFor(world,'A').title,'未竟之案');s.evidence={E1:'verified',E2:'verified',E3:'verified',E4:'pending'};s.oldCaseSubmitted=true;s.support={government:['立案'],civil:['救援']};assert.equal(endingFor(world,'A').title,'未竟之案');s.evidence.E4='verified';assert.equal(endingFor(world,'A').title,'公堂有燈');assert.equal(endingFor(world,'B').title,'江上暫平');assert.equal(endingFor(world,'C').title,'未竟之案');s.support.sects=['護送'];assert.equal(endingFor(world,'C').title,'無旗之盟');s.losses=['mill','ship','forced_gate'];assert.equal(endingFor(world,'A').title,'公堂有燈');assert.equal(endingFor(world,'A').memorial,'名字留在渡口');s.oldCaseSubmitted=false;assert.equal(endingFor(world,'B').title,'未竟之案');});
test('secret ship signal has a visible fallback and never locks the story',()=>{const {world,engine}=fresh();world.chapter=8;world.currentSceneId='8-2B';assert.deepEqual(engine.sceneView().choices.map(c=>c.id),['A','C']);engine.choose('A');assert.equal(world.zhaoye.facilities.lowerGate,undefined);engine.choose('operate');engine.choose('operate');assert.equal(world.zhaoye.facilities.lowerGate,1);assert.equal(world.zhaoye.facilities.signal,1);});
test('public rescue funds are isolated from personal money',()=>{const {world,character,engine}=fresh();world.currentSceneId='1-4';engine.choose('B');assert.equal(character.moneyWen,1000);assert.equal(world.zhaoye.publicFunds,120);});
