import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import vm from 'node:vm';
import { createWorld, GameEngine } from '../src/core/game-engine.js';
import { createZhaoyeState } from '../src/core/zhaoye-engine.js';
import { ZHAOYE_SCRIPT } from '../src/data/zhaoye-script.js';
import { REACTIONS } from '../src/core/zhaoye-reactions.js';
import { calculateRealm } from '../src/systems/realm-system.js';
import { BattleSystem } from '../src/systems/battle-system.js';
import { SeededRng } from '../src/core/rng.js';

function setup(){const world=createWorld({name:'測試',startingCountry:'dasheng',ownerCharacterId:'hero',seed:'test'});world.zhaoye=createZhaoyeState();world.currentSceneId='1-0';return {world,engine:new GameEngine({world,character:{moneyWen:100},content:{}})};}
test('all supplemental choices have authored immediate reactions, not one generic acknowledgement',()=>{for(const event of ZHAOYE_SCRIPT.filter(s=>/[A-D]$/.test(s.id))){assert.equal(REACTIONS[event.id]?.length,3,event.id);assert.equal(new Set(REACTIONS[event.id]).size,3,event.id);}});
test('investigation text does not expose the answers or future callbacks before choosing',()=>{const {world,engine}=setup();world.currentSceneId='1-1A';const text=engine.sceneView().text;assert.ok(!text.includes('指腹留墨'));assert.ok(!text.includes('解鎖'));assert.ok(!text.includes('- A'));});
test('Tao and messenger branch narration never displays both life and death variants',()=>{const {world,engine}=setup();world.currentSceneId='1-3B';world.zhaoye.taoAlive=false;assert.ok(!engine.sceneView().text.includes('隔著屏風說'));world.zhaoye.taoAlive=true;assert.ok(engine.sceneView().text.includes('隔著屏風說'));world.currentSceneId='8-3A';world.zhaoye.messengerAlive=false;assert.ok(!engine.sceneView().text.includes('縮在牆邊'));world.zhaoye.messengerAlive=true;assert.ok(!engine.sceneView().text.includes('醫工確認後覆上布'));});
test('realm is determined by actual training, not chapter, spare money or unused cultivation',()=>{const c={skills:{a:{realm:0,completeness:1}},meridians:{},innerArts:{},moneyWen:1e9,cultivation:1e9,chapter:8};assert.equal(calculateRealm(c).realm,0);c.skills.a.realm=4;assert.equal(calculateRealm(c).realm,1);c.skills.a.completeness=.1;assert.equal(calculateRealm(c).realm,0);});
test('scenario operations consume an actual living actor action, without a free attack or defense',()=>{const {world,engine}=setup();world.currentSceneId='1-3';engine.choose('A');const actor={id:'hero',name:'你',side:'party',hp:100,maxHp:100,posture:90,maxPosture:90,inner:50,maxInner:50,stats:{agility:20},skills:[],statuses:[],vulnerableTurns:0};const battle=new BattleSystem({party:[actor],enemies:[],rng:new SeededRng('objective')});battle.onScenarioAction=round=>engine.battleAction('objective',round);battle.resolve(actor,{type:'objective'});assert.equal(world.zhaoye.events['1-3'].actions,1);assert.equal(actor.defended,false);assert.ok(battle.log.at(-1).includes('不另攻擊或防禦'));});
test('offline shell includes every static imported module, and activation preserves other apps caches',async()=>{const handlers={},deleted=[];const ctx={self:{registration:{scope:'https://example.test/7414/'},location:{origin:'https://example.test'},addEventListener:(k,v)=>handlers[k]=v,clients:{claim:()=>{}}},caches:{keys:async()=>['other-app-cache','jianghu-rpg:https://example.test/other/:0.2.0','jianghu-rpg:https://example.test/7414/:0.2.0'],delete:async key=>deleted.push(key)}};vm.createContext(ctx);vm.runInContext(readFileSync(new URL('../sw.js',import.meta.url),'utf8')+'\nthis.precache=SHELL;',ctx);for(const url of ctx.precache){if(url==='./')continue;assert.ok(existsSync(new URL('../'+url.slice(2),import.meta.url)),url);}const seen=new Set();function inspect(relative){if(seen.has(relative))return;seen.add(relative);const file=new URL('../'+relative,import.meta.url);for(const [,target] of readFileSync(file,'utf8').matchAll(/(?:from\s+|import\s*)["'](\.[^"']+)["']/g)){const resolved=new URL(target,file);const root=new URL('../',import.meta.url);const local=resolved.href.slice(root.href.length);assert.ok(ctx.precache.includes('./'+local),`Missing offline import: ${local}`);inspect(local);}}inspect('src/app.js');let task;handlers.activate({waitUntil:p=>task=p});await task;assert.deepEqual(deleted,['jianghu-rpg:https://example.test/7414/:0.2.0']);});
