import {availableJourneyEvents,journey,journeyStatus,flowSummary,JOURNEY_PLACES} from '../systems/exploration-system.js';
import {INVESTIGATIONS,ZHAOYE_LOCATION_IDS,ZHAOYE_ORDER,ZHAOYE_PLACES,ZHAOYE_SCENES} from '../core/zhaoye-story.js';
import {REACTIONS} from '../core/zhaoye-reactions.js';
import {COUNTRIES} from '../config/constants.js';
import {skillArtStyle} from './skill-art.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function chapterOneDestination(world){if(!world.zhaoye||world.chapter!==1||world.zhaoye.chapterSafe||world.currentSceneId==='1-0'||world.currentLocationId===ZHAOYE_LOCATION_IDS[0])return null;const scene=ZHAOYE_SCENES[world.currentSceneId];return scene?.chapter===1?{id:ZHAOYE_LOCATION_IDS[0],place:ZHAOYE_PLACES[0],action:scene.title}:null;}
const MAP_REGIONS=[['dasheng','大晟'],['beishuo','北朔'],['nanli','南黎'],['cross_border','邊境與渡口']];
export function routeDiagram(world,locations,targetId=null){
 const current=locations.find(location=>location.id===world.currentLocationId);
 const renderNode=location=>{
  const here=location.id===world.currentLocationId,storyTarget=location.id===targetId;
  const journeyEvents=availableJourneyEvents(world,location.id);
  const status=journeyStatus(world,location.id);
  const fast=world.visitedLocations.includes(location.id)&&location.type==='city';
  const action=here?'':`<div class="route-node-actions"><button class="btn" data-travel="${location.id}">前往${esc(location.name)}</button>${fast?`<button class="btn" data-fast-travel="${location.id}">搭驛站 · 80 文</button>`:''}</div>`;
  const art=/^location_\d{3}$/.test(location.id)?` style="--place-art:url('../assets/locations/${location.id}.jpg')"`:'';
  return `<article class="route-node ${here?'current':''} ${storyTarget?'mainline-target':''}"${art} ${here?'id="map-current" aria-current="location"':''}><div class="route-node-head"><h4>${esc(location.name)}</h4>${here?'<span class="map-badge map-badge-here">你在此</span>':''}${storyTarget?'<span class="map-badge map-badge-target">主線目的地</span>':''}${journeyEvents.length?'<span class="map-badge map-badge-event">新事</span>':''}</div><p class="route-node-status">${esc(status)}</p>${JOURNEY_PLACES.includes(location.id)&&journeyEvents.length?`<p class="route-node-event">${journeyEvents.map(event=>esc(event.title)).join('／')}</p>`:''}${action}</article>`;
 };
 return `<section class="route-diagram" aria-label="三國與邊境行路圖">${MAP_REGIONS.map(([id,label])=>`<section class="map-region ${id==='cross_border'?'map-region-border':''} ${current?.country===id?'map-region-current':''}" data-country="${id}" aria-label="${label}"><header class="map-region-head"><h3>${label}</h3><span>${current?.country===id?'目前所在區域 · ':''}${locations.filter(location=>location.country===id).length} 處地點</span></header><div class="map-region-list">${locations.filter(location=>location.country===id).map(renderNode).join('')}</div></section>`).join('')}</section>`;
}
export function loadoutView(character,content){return `<h3>六格配招</h3><div class="loadout-slots">${Array.from({length:6},(_,i)=>{const skill=content.skills.find(s=>s.id===character.equippedSkills[i]);return `<div class="${skill?'skill-art-card loadout-art-card':''}" ${skill?skillArtStyle(skill):''}><small>第 ${i+1} 式</small><strong>${esc(skill?.name??'待配招')}</strong></div>`;}).join('')}</div><p>已運行：${Object.entries(character.innerArts).filter(([,a])=>a.active).map(([id])=>esc(content.innerArts.find(a=>a.id===id)?.name)).join('、')||'尚無內功'}</p><p>配裝：${Object.values(character.equipment).map(id=>esc(content.equipment.find(e=>e.id===id)?.name)).filter(Boolean).join('、')||'尚未裝備'}</p><p>裝備與天賦合計：傷害 ${Math.round((character.damagePct??0)*100)}% · 破勢 ${Math.round((character.postureDamagePct??0)*100)}% · 減傷 ${Math.round((character.damageReduction??0)*100)}%</p>`;}
export function locationEvents(world){const list=availableJourneyEvents(world);return `<section class="journey-card"><p class="eyebrow">此地江湖</p>${list.length?list.map(e=>`<article><h3>${esc(e.title)}</h3><p>${esc(e.text)}</p><div class="choices"><button class="btn btn-primary" data-journey="${e.id}">${esc(e.label)}</button>${e.id==='flow_fragment'?'<button class="btn" data-journey-decline="flow_fragment">不受教，以交手參悟</button>':''}</div></article>`).join(''):'<p>此地暫無新奇遇。可查看地圖追尋線索，或繼續主線。</p>'}<p class="muted">奇遇可暫緩；切換地圖或主線不會錯過此事件。</p></section>`;}
export function mapView(world,locations){
 const current=locations.find(location=>location.id===world.currentLocationId),target=chapterOneDestination(world);
 return `<p class="eyebrow">山河有路 · 第 ${world.clock.day} 日</p><h2>江湖輿圖</h2><section class="map-position" aria-label="目前所在地"><div><p class="map-position-label">你在這裡</p><h3>${esc(current?.name??'未知地點')}</h3><p>${esc(COUNTRIES[current?.country]?.name??'邊境與渡口')} · 第 ${world.clock.day} 日</p><a class="map-find-me" href="#map-current">在圖上找我 ↓</a></div><div class="map-next-routes"><strong>任選目的地，直接出發</strong><p>下方每個地點都可前往，不必經過相鄰城鎮。</p>${target?`<div><button class="btn" data-travel="${target.id}">前往主線現場：${esc(target.place)}</button></div>`:''}<small>一般移動免費、耗兩個時段；已到訪城市可付 80 文搭驛站，只耗一個時段。</small></div></section>${target?`<p class="mainline-route"><strong>主線目的地：${esc(target.place)}</strong> · 抵達後繼續「${esc(target.action)}」。可直接從地圖前往。</p>`:''}<div class="map-key" aria-label="地圖標記說明"><span><b class="map-key-here"></b>你在此</span><span><b class="map-key-target"></b>主線目的地</span><span><b class="map-key-event"></b>可進行奇遇</span></div>${routeDiagram(world,locations,target?.id)}<details><summary>文字地點清單（可直接前往）</summary><ul class="map-text-list">${locations.map(location=>{const here=location.id===world.currentLocationId,fast=world.visitedLocations.includes(location.id)&&location.type==='city';return `<li><span><strong>${esc(location.name)}</strong> · ${esc(COUNTRIES[location.country]?.name??'邊境與渡口')}</span>${here?'<span>目前所在地</span>':`<div><button class="btn" data-travel="${location.id}">前往${esc(location.name)}</button>${fast?`<button class="btn" data-fast-travel="${location.id}">搭驛站前往${esc(location.name)}</button>`:''}</div>`}</li>`;}).join('')}</ul></details>`;
}
export function flowView(world,character){const f=flowSummary(world,character);return `<section class="flow-banner"><p class="eyebrow">破勢連攻 · ${['未入門','入門','成形','大成'][f.stage]}</p><h2>${esc(f.effect)}</h2><p>${f.equipped?'八方拳已裝入配招。':'需將八方拳裝入六格配招，連攻才會生效。'}</p><p><strong>下一步：</strong>${esc(f.next)}</p></section>`;}
function chapterOneInvestigationJournal(world){const events=world.zhaoye?.events??{},records=ZHAOYE_ORDER.filter(id=>INVESTIGATIONS.has(id)&&ZHAOYE_SCENES[id]?.chapter===1).flatMap(id=>(events[id]?.investigations??[]).map(choiceId=>({scene:ZHAOYE_SCENES[id],choiceId,label:ZHAOYE_SCENES[id].choices.find(choice=>choice.id===choiceId)?.label??choiceId,text:REACTIONS[id]?.['ABCD'.indexOf(choiceId)]})));if(!records.length)return '<h3>主線調查紀錄</h3><p>第一章的現場發現會收在這裡，方便回看已查到的線索。</p>';return `<h3>主線調查紀錄 · 第一章</h3><details class="journal-investigations"><summary>已記錄 ${records.length} 項調查發現</summary><ol>${records.map(record=>`<li><h4>${esc(record.scene.title)} · ${esc(record.label)}</h4><p>${esc(record.text??'這項材料已列入案卷，仍待後續線索核對。')}</p></li>`).join('')}</ol></details>`;}
function mainlineJournal(world){
 if(world.flags?.game_complete)return '<section class="mainline-journal"><h3>主線待辦</h3><p>八章主線已完成。</p></section>';
 if(world.zhaoye?.chapterSafe)return `<section class="mainline-journal"><h3>主線待辦 · 第 ${world.chapter} 章</h3><p>本章已告一段落；返回江湖查看章後待辦與啟程選項。</p></section>`;
 const scene=world.zhaoye?ZHAOYE_SCENES[world.currentSceneId]:null;
 if(!scene)return `<section class="mainline-journal"><h3>主線待辦</h3><p>第 ${world.chapter} 章 · 返回江湖查看眼前案卷。</p></section>`;
 const awayFromYadu=scene.chapter===1&&scene.id!=='1-0'&&world.currentLocationId!==ZHAOYE_LOCATION_IDS[0];
 const next=awayFromYadu?`前往${ZHAOYE_PLACES[0]}，抵達後繼續「${scene.title}」。`:`返回江湖繼續「${scene.title}」。`;
 return `<section class="mainline-journal"><h3>主線待辦 · 第 ${world.chapter} 章</h3><p><strong>${esc(scene.title)}</strong></p><p>${esc(next)}</p></section>`;
}
export function journalView(world,character){const j=journey(world),f=flowSummary(world,character);return `<p class="eyebrow">江湖留痕 · 名號：${esc(f.title)}</p><h2>主線與奇遇</h2>${mainlineJournal(world)}${chapterOneInvestigationJournal(world)}<h3>鏢路拳譜奇遇</h3><p><strong>奇遇下一步：</strong>${esc(f.next)}</p><h3>探索記事</h3>${j.notes.length?`<ol>${j.notes.map(n=>`<li>${esc(n)}</li>`).join('')}</ol>`:'<p>尚未展開鏢路拳譜奇遇。</p>'}<h3>承諾與履約</h3>${Object.values(world.zhaoye?.promises??{}).map(p=>`<p><strong>${esc(p.who)}</strong> · ${esc(p.what)} · ${esc(p.where)} · ${({fulfilled:'已履行',refused:'已拒絕',pending:'待履約'})[p.status]??'待核對'}</p>`).join('')||'<p>目前沒有待履約紀錄。</p>'}<p>主線承諾與待履約事件請返回江湖查看。</p>`;}
export function combatFeedback(battle){const labels={break:'架勢崩解',follow:'破勢追加',chase:'追擊下一人',kill:'擊倒',refund:'回復內力',heal:'回復氣血'};const buffs={damage:'氣血傷害',posture:'削架勢',defense:'減傷',speed:'速度'};return `<div class="combat-feedback" role="status">${(battle.events??[]).filter(e=>e.type==='hit'&&e.actorId===battle.party[0]?.id).map(e=>`<span>氣血 −${e.hpDamage} · 架勢 −${e.postureDamage}</span>`).join('')}${(battle.events??[]).filter(e=>labels[e.type]).map(e=>`<span class="chip">${labels[e.type]}${e.amount!=null?' +'+e.amount:''}</span>`).join('')}${(battle.events??[]).filter(e=>e.type==='buff').map(e=>`<span class="chip">全隊${buffs[e.stat]??'能力'} +${Math.round(e.value*100)}%</span>`).join('')}</div>`;}
