import {availableJourneyEvents,journey,journeyStatus,flowSummary,JOURNEY_PLACES} from '../systems/exploration-system.js';
import {INVESTIGATIONS,ZHAOYE_LOCATION_IDS,ZHAOYE_ORDER,ZHAOYE_PLACES,ZHAOYE_SCENES} from '../core/zhaoye-story.js';
import {REACTIONS} from '../core/zhaoye-reactions.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function chapterOneDestination(world){if(!world.zhaoye||world.chapter!==1||world.zhaoye.chapterSafe||world.currentSceneId==='1-0'||world.currentLocationId===ZHAOYE_LOCATION_IDS[0])return null;const scene=ZHAOYE_SCENES[world.currentSceneId];return scene?.chapter===1?{id:ZHAOYE_LOCATION_IDS[0],place:ZHAOYE_PLACES[0],action:scene.title}:null;}
export function routeDiagram(world,locations,targetId=null){const points=locations.map((l,i)=>{const angle=i/locations.length*Math.PI*2-Math.PI/2;return {id:l.id,x:400+290*Math.cos(angle),y:280+210*Math.sin(angle),name:l.name};});return `<svg class="route-diagram" viewBox="0 0 800 560" role="img" aria-label="江湖環形路線，朱圈標記主線目的地，完整地點與操作見下方清單"><title>江湖路線</title>${points.flatMap(p=>locations.find(l=>l.id===p.id).adjacentIds.filter(id=>id>p.id).map(id=>{const q=points.find(x=>x.id===id);return `<line x1="${p.x}" y1="${p.y}" x2="${q.x}" y2="${q.y}"/>`;})).join('')}${points.map(p=>`<g class="${[p.id===world.currentLocationId?'here':'',p.id===targetId?'story-target':''].filter(Boolean).join(' ')}"><circle cx="${p.x}" cy="${p.y}" r="${p.id===world.currentLocationId?9:p.id===targetId?8:5}"/><text x="${p.x}" y="${p.y-17}" text-anchor="middle">${esc(p.name)}</text>${p.id===targetId?`<text class="map-target-dot" x="${p.x+13}" y="${p.y+5}">◎</text>`:''}${availableJourneyEvents(world,p.id).length?`<text class="map-event-dot" x="${p.x+13}" y="${p.y+5}">◆</text>`:''}</g>`).join('')}<text x="400" y="260" text-anchor="middle" class="map-title">照夜行</text><text x="400" y="294" text-anchor="middle">朱點為所在 · 朱圈為主線目的地 · 菱記為新事</text></svg>`;}
export function loadoutView(character,content){return `<h3>六格配招</h3><div class="loadout-slots">${Array.from({length:6},(_,i)=>`<div><small>第 ${i+1} 式</small><strong>${esc(content.skills.find(s=>s.id===character.equippedSkills[i])?.name??'待配招')}</strong></div>`).join('')}</div><p>已運行：${Object.entries(character.innerArts).filter(([,a])=>a.active).map(([id])=>esc(content.innerArts.find(a=>a.id===id)?.name)).join('、')||'尚無內功'}</p><p>配裝：${Object.values(character.equipment).map(id=>esc(content.equipment.find(e=>e.id===id)?.name)).filter(Boolean).join('、')||'尚未裝備'}</p><p>裝備與天賦合計：傷害 ${Math.round((character.damagePct??0)*100)}% · 破勢 ${Math.round((character.postureDamagePct??0)*100)}% · 減傷 ${Math.round((character.damageReduction??0)*100)}%</p>`;}
export function locationEvents(world){const list=availableJourneyEvents(world);return `<section class="journey-card"><p class="eyebrow">此地江湖</p>${list.length?list.map(e=>`<article><h3>${esc(e.title)}</h3><p>${esc(e.text)}</p><div class="choices"><button class="btn btn-primary" data-journey="${e.id}">${esc(e.label)}</button>${e.id==='flow_fragment'?'<button class="btn" data-journey-decline="flow_fragment">不受教，以交手參悟</button>':''}</div></article>`).join(''):'<p>此地暫無新奇遇。可查看地圖追尋線索，或繼續主線。</p>'}<p class="muted">奇遇可暫緩；切換地圖或主線不會錯過此事件。</p></section>`;}
export function mapView(world,locations){const current=locations.find(l=>l.id===world.currentLocationId),target=chapterOneDestination(world);return `<p class="eyebrow">山河有路 · 第 ${world.clock.day} 日</p><h2>江湖輿圖</h2><p>目前位於 <strong>${esc(current?.name)}</strong>。步行兩個時段；已訪城市可付 80 文搭驛站，一個時段。</p>${target?`<p class="mainline-route"><strong>主線目的地：${esc(target.place)}</strong> · 抵達後繼續「${esc(target.action)}」。沿相鄰路線步行；首次抵達不收驛站費。</p>`:''}${routeDiagram(world,locations,target?.id)}<div class="route-grid" aria-label="地點及相鄰路線">${locations.map(l=>`<article class="route-node ${l.id===current?.id?'current':''} ${l.id===target?.id?'mainline-target':''}"><h3>${esc(l.name)}</h3><span class="chip">${esc(journeyStatus(world,l.id))}</span>${l.id===target?.id?'<span class="chip">主線目的地</span>':''}<p>相接：${l.adjacentIds.map(id=>esc(locations.find(x=>x.id===id)?.name)).join('、')}</p>${JOURNEY_PLACES.includes(l.id)?`<p>${availableJourneyEvents(world,l.id).map(e=>esc(e.title)).join('／')||'鏢路拳譜所經之地'}</p>`:''}${l.id===current?.id?'<strong>你在此處</strong>':current?.adjacentIds.includes(l.id)?`<button class="btn" data-travel="${l.id}">步行前往</button>`:world.visitedLocations.includes(l.id)&&l.type==='city'?`<button class="btn" data-fast-travel="${l.id}">驛站 · 80 文</button>`:'<span class="muted">沿相鄰路線前往</span>'}</article>`).join('')}</div><details><summary>文字路線清單</summary>${locations.map(l=>`<p>${esc(l.name)} → ${l.adjacentIds.map(id=>esc(locations.find(x=>x.id===id)?.name)).join('／')}</p>`).join('')}</details>`;}
export function flowView(world,character){const f=flowSummary(world,character);return `<section class="flow-banner"><p class="eyebrow">破勢連攻 · ${['未入門','入門','成形','大成'][f.stage]}</p><h2>${esc(f.effect)}</h2><p>${f.equipped?'八方拳已裝入配招。':'需將八方拳裝入六格配招，連攻才會生效。'}</p><p><strong>下一步：</strong>${esc(f.next)}</p></section>`;}
function chapterOneInvestigationJournal(world){const events=world.zhaoye?.events??{},records=ZHAOYE_ORDER.filter(id=>INVESTIGATIONS.has(id)&&ZHAOYE_SCENES[id]?.chapter===1).flatMap(id=>(events[id]?.investigations??[]).map(choiceId=>({scene:ZHAOYE_SCENES[id],choiceId,label:ZHAOYE_SCENES[id].choices.find(choice=>choice.id===choiceId)?.label??choiceId,text:REACTIONS[id]?.['ABCD'.indexOf(choiceId)]})));if(!records.length)return '<h3>主線調查紀錄</h3><p>第一章的現場發現會收在這裡，方便回看已查到的線索。</p>';return `<h3>主線調查紀錄 · 第一章</h3><details class="journal-investigations"><summary>已記錄 ${records.length} 項調查發現</summary><ol>${records.map(record=>`<li><h4>${esc(record.scene.title)} · ${esc(record.label)}</h4><p>${esc(record.text??'這項材料已列入案卷，仍待後續線索核對。')}</p></li>`).join('')}</ol></details>`;}
function mainlineJournal(world){
 if(world.flags?.game_complete)return '<section class="mainline-journal"><h3>主線待辦</h3><p>八章主線已完成。</p></section>';
 if(world.zhaoye?.chapterSafe)return `<section class="mainline-journal"><h3>主線待辦 · 第 ${world.chapter} 章</h3><p>本章已告一段落；返回江湖查看章後待辦與啟程選項。</p></section>`;
 const scene=world.zhaoye?ZHAOYE_SCENES[world.currentSceneId]:null;
 if(!scene)return `<section class="mainline-journal"><h3>主線待辦</h3><p>第 ${world.chapter} 章 · 返回江湖查看眼前案卷。</p></section>`;
 const awayFromYadu=scene.chapter===1&&scene.id!=='1-0'&&world.currentLocationId!==ZHAOYE_LOCATION_IDS[0];
 const next=awayFromYadu?`前往${ZHAOYE_PLACES[0]}，抵達後繼續「${scene.title}」。`:`返回江湖繼續「${scene.title}」。`;
 return `<section class="mainline-journal"><h3>主線待辦 · 第 ${world.chapter} 章</h3><p><strong>${esc(scene.title)}</strong></p><p>${esc(next)}</p></section>`;
}
export function journalView(world,character){const j=journey(world),f=flowSummary(world,character);return `<p class="eyebrow">江湖留痕 · 名號：${esc(f.title)}</p><h2>主線與奇遇</h2>${mainlineJournal(world)}${chapterOneInvestigationJournal(world)}<h3>鏢路拳譜奇遇</h3><p><strong>奇遇下一步：</strong>${esc(f.next)}</p><h3>探索記事</h3>${j.notes.length?`<ol>${j.notes.map(n=>`<li>${esc(n)}</li>`).join('')}</ol>`:'<p>尚未展開鏢路拳譜奇遇。</p>'}<h3>承諾與履約</h3>${Object.values(world.zhaoye?.promises??{}).map(p=>`<p><strong>${esc(p.who)}</strong> · ${esc(p.what)} · ${esc(p.where)} · ${({fulfilled:'已履行',refused:'已拒絕',pending:'待履約'})[p.status]??'待核對'}</p>`).join('')||'<p>目前沒有待履約紀錄。</p>'}<p>主線承諾與待履約事件請返回江湖查看。</p>`;}
export function combatFeedback(battle){const labels={break:'架勢崩解',follow:'破勢追加',chase:'追擊下一人',kill:'擊倒',refund:'回復內力'};return `<div class="combat-feedback" role="status">${(battle.events??[]).filter(e=>e.type==='hit'&&e.actorId===battle.party[0]?.id).map(e=>`<span>氣血 −${e.hpDamage} · 架勢 −${e.postureDamage}</span>`).join('')}${(battle.events??[]).filter(e=>labels[e.type]).map(e=>`<span class="chip">${labels[e.type]}${e.amount!=null?' +'+e.amount:''}</span>`).join('')}</div>`;}
