const STAT_KEYS={1:"strength",2:"constitution",3:"agility",4:"comprehension",5:"willpower",16:"strength",17:"constitution",18:"agility",19:"comprehension",20:"willpower",42:"comprehension",43:"constitution",44:"willpower",46:"agility",49:"agility",50:"willpower"};
const STAT_VALUES={1:5,2:5,3:5,4:5,5:5,16:9,17:9,18:9,19:9,20:9,42:12,43:12,44:-8,46:10,49:-8,50:-10};

export function talentModifiers(talentIds=[]){
  const result={statFlat:{strength:0,constitution:0,agility:0,comprehension:0,willpower:0},hpPct:0,innerPct:0,posturePct:0,speedFlat:0,proficiencyPct:0,innerProficiencyPct:0,statTrainingPct:0,damagePct:0,damageTakenPct:0,postureDamagePct:0,postureDamageTakenPct:0,healingPct:0,observationPct:0,situationalDamagePct:0,lateTurnDamagePct:0,guardReductionPct:0,survivalHealPct:0,normalAttackReductionPct:0,lowHpWillpowerFlat:0};
  for(const id of talentIds){const index=Number(String(id).split("_").at(-1));const stat=STAT_KEYS[index];if(stat)result.statFlat[stat]+=STAT_VALUES[index];
    if(index===6)result.innerPct+=.08;else if(index===7)result.hpPct+=.08;else if(index===8)result.speedFlat+=4;else if(index===9)result.proficiencyPct+=.08;else if(index===10)result.innerProficiencyPct+=.08;else if(index===11)result.normalAttackReductionPct+=.05;else if(index===12)result.postureDamagePct+=.08;else if(index===13)result.posturePct+=.1;else if(index===14)result.observationPct+=.1;else if(index===15)result.guardReductionPct+=.08;
    else if(index===21)result.innerPct+=.15;else if(index===22)result.hpPct+=.15;else if(index===23)result.proficiencyPct+=.12;else if(index===24)result.innerProficiencyPct+=.12;else if(index===25)result.postureDamagePct+=.15;else if(index===26)result.postureDamageTakenPct-=.12;else if(index===27)result.healingPct+=.15;else if(index===28)result.lowHpWillpowerFlat+=15;else if(index===29)result.lateTurnDamagePct+=.1;else if(index===30)result.guardReductionPct+=.15;
    else if(index===31)result.proficiencyPct+=.2;else if(index===32)result.innerProficiencyPct+=.2;else if(index===33){result.hpPct+=.2;result.damageTakenPct-=.05;}else if(index===34){result.innerPct+=.2;result.innerProficiencyPct+=.1;}else if(index===35)result.observationPct+=.25;else if(index===36)result.posturePct+=.25;else if(index===37)result.postureDamagePct+=.25;else if(index===38)result.situationalDamagePct+=.12;else if(index===39)result.survivalHealPct+=.1;else if(index===40){result.proficiencyPct+=.25;result.statTrainingPct+=.1;}else if(index===41){result.innerPct+=.3;result.innerProficiencyPct+=.15;}else if(index===42)result.observationPct+=.2;else if(index===43){result.hpPct+=.2;result.posturePct+=.15;}else if(index===44)result.proficiencyPct+=.15;else if(index===45){result.damagePct+=.1;result.damageTakenPct+=.08;}else if(index===46)result.hpPct-=.1;else if(index===47)result.hpPct-=.15;else if(index===48)result.innerPct-=.15;
  }
  return result;
}

export function applyTalentModifiers(character){const modifiers=talentModifiers(character.talents);character.talentModifiers=modifiers;character.effectiveStats=Object.fromEntries(Object.entries(character.stats).map(([key,value])=>[key,Math.max(1,Math.min(100,value+(modifiers.statFlat[key]??0)))]));return character;}
