import fs from "node:fs";
import { SeededRng } from "../src/core/rng.js";
import { BattleSystem, makeEnemy, makeNpcCompanion, makePlayerCombatant } from "../src/systems/battle-system.js";
import { IDENTITIES } from "../src/config/constants.js";
import { deriveResources } from "../src/config/balance.js";

const read=name=>JSON.parse(fs.readFileSync(new URL(`../src/data/${name}.json`,import.meta.url),"utf8")).data;
const skills=read("skills"),enemies=read("enemies");
const byName=name=>skills.find(s=>s.name===name);
const trials=80;

function simulate(skill,enemyDef,seed){const builds={attack:{strength:30,constitution:25,agility:20,comprehension:10,willpower:15},posture:{strength:30,constitution:25,agility:20,comprehension:10,willpower:15},control:{strength:15,constitution:25,agility:25,comprehension:20,willpower:15},defense:{strength:15,constitution:35,agility:15,comprehension:15,willpower:20},guard:{strength:15,constitution:30,agility:20,comprehension:15,willpower:20},mobility:{strength:15,constitution:25,agility:30,comprehension:15,willpower:15}};const stats=builds[skill.type];const resources=deriveResources(stats);const character={id:"hero",name:"俠客",stats,equippedSkills:[skill.id],...resources};const rng=new SeededRng(seed);const battle=new BattleSystem({party:[makePlayerCombatant(character,skills),makeNpcCompanion("陸小川",skills)],enemies:[makeEnemy(enemyDef,skills,2)],rng});let rounds=0;while(!battle.finished&&rounds<80){const hero=battle.living("party")[0],target=battle.living("enemy")[0];if(!hero||!target)break;let action;if(hero.hp/hero.maxHp<.3&&hero.consumablesUsed<3)action={type:"item"};else if(hero.posture/hero.maxPosture<.22)action={type:"defend"};else if(skill.type==="attack"&&skill.innerCost<=hero.inner)action={type:"skill",skillId:skill.id,targetId:target.id};else if(skill.type==="posture"&&target.posture/target.maxPosture>.35&&skill.innerCost<=hero.inner)action={type:"skill",skillId:skill.id,targetId:target.id};else if(skill.type==="control"&&rounds%3===0&&skill.innerCost<=hero.inner)action={type:"skill",skillId:skill.id,targetId:target.id};else if(skill.type==="mobility"&&target.intent?.type==="skill"&&hero.hp/hero.maxHp<.6&&skill.innerCost<=hero.inner)action={type:"skill",skillId:skill.id,targetId:target.id};else if(skill.type==="defense"&&target.intent?.type==="skill"&&hero.hp/hero.maxHp<.6&&skill.innerCost<=hero.inner)action={type:"skill",skillId:skill.id,targetId:target.id};else if(skill.type==="guard"&&battle.living("party").some(a=>a.id==="npc_001"&&a.hp/a.maxHp<.4)&&skill.innerCost<=hero.inner)action={type:"skill",skillId:skill.id,targetId:"npc_001"};else action={type:"attack",targetId:target.id};battle.submit(action);rounds++;}return {win:battle.finished==="victory",rounds};}

for(const [label,enemy] of [["教學戰",enemies[0]],["第一章 Boss",enemies[3]]]){const rows=[];for(const identity of IDENTITIES){for(const skillName of identity.skills){const skill=byName(skillName);let wins=0,totalRounds=0;for(let i=0;i<trials;i++){const result=simulate(skill,enemy,`${label}-${skill.id}-${i}`);wins+=result.win;totalRounds+=result.rounds;}rows.push({身份:identity.name,武功:skill.name,勝率:`${Math.round(wins/trials*100)}%`,平均回合:+(totalRounds/trials).toFixed(1)});} }console.log(`\n${label}`);console.table(rows);const rates=rows.map(r=>Number(r.勝率.slice(0,-1))),spread=Math.max(...rates)-Math.min(...rates);console.log(`勝率差：${spread} 個百分點`);if(label.includes("Boss")&&(Math.min(...rates)<55||spread>40)){console.error("平衡門檻失敗：最佳化起始配置勝率需至少 55%，選項差距不得超過 40 個百分點。");process.exitCode=1;}}
