// Mechanical content import. The original is retained as a design source, never executed.
import { readFileSync, writeFileSync } from 'node:fs';
const input = process.argv[2];
if (!input) throw new Error('Pass the authored markdown path');
const source = readFileSync(input, 'utf8').replace(/\r/g, '');
const matches = [...source.matchAll(/^### (\d-\d+[A-D]?) ([^\n]+)\n([\s\S]*?)(?=^### |^## |$(?![\s\S]))/gm)];
const clean = s => s.replace(/\*\*/g, '').replace(/^旁白：/gm, '').trim();
const events = matches.map(m => {
  const [,id,title,body] = m;
  const markers=[body.indexOf('**選項與接續：**'),body.search(/^- A「/m)].filter(n=>n>=0);
  const optionStart = markers.length?Math.min(...markers):-1;
  const narrative = (optionStart >= 0 ? body.slice(0, optionStart) : body).split('\n\n').filter(p => !/^【|^主持|^---|^####/.test(p.trim()));
  const options = [...body.matchAll(/^- ([ABC])「([^\n]+?)」([^\n]*)/gm)].map(([,id,label,result])=>({id,label,result:clean(result)}));
  return {id,chapter:Number(id[0]),title:clean(title),optional:/【可選/.test(body),text:clean(narrative.join('\n\n')),options,source:body.trim()};
});
const unique = [...new Map(events.map(e => [e.id,e])).values()];
if (unique.filter(e=>/[A-D]$/.test(e.id)).length!==64) throw new Error('Expected exactly 64 supplemental events');
writeFileSync(new URL('../src/data/zhaoye-script.js',import.meta.url), '// Generated by scripts/import-zhaoye.mjs; do not edit.\nexport const ZHAOYE_SCRIPT = '+JSON.stringify(unique,null,2)+';\n');
console.log(`Imported ${unique.length} scenes, 64 supplemental events.`);
