import { loadContent } from "./data/loader.js";
import { COUNTRIES, DEFAULT_STATS, IDENTITIES, STAT_LABELS } from "./config/constants.js";
import { SeededRng } from "./core/rng.js";
import { GameEngine, createWorld } from "./core/game-engine.js";
import { CLUE_LABELS } from "./core/story.js";
import { createCharacter, rollStartingTalents } from "./systems/progression-system.js";
import { BattleSystem, makeEnemy, makeNpcCompanion, makePlayerCombatant } from "./systems/battle-system.js";
import { factionLabel } from "./systems/faction-system.js";
import { saveGame, loadSlot, getAllSaves, importSaves, listSlots } from "./persistence/save-service.js";
import { createExportBundle, downloadJson, parseImport } from "./persistence/import-export.js";
import { LocalRoomTransport } from "./multiplayer/local-transport.js";
import { RoomController } from "./multiplayer/room-controller.js";

const app = document.querySelector("#app");
const state = { screen:"boot", content:null, character:null, world:null, engine:null, rng:new SeededRng(`jianghu-${Date.now()}`), battle:null, pendingBattleChoice:null, modal:null, modalTrigger:null, talentRoll:null, talentRerolled:false, creator:{ stats:{...DEFAULT_STATS}, identityId:IDENTITIES[0].id, selectedTalentId:null }, room:null };

boot();

if ("serviceWorker" in navigator && location.protocol !== "file:") window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));

async function boot() {
  try { state.content=await loadContent(); state.screen="home"; render(); }
  catch(error){app.innerHTML=`<main class="boot-screen"><p class="eyebrow">內容驗證失敗</p><h1>案卷無法展開</h1><p class="danger">${escapeHtml(error.message)}</p></main>`;console.error(error);}
}

function render() {
  if(state.screen==="home")renderHome();
  else if(state.screen==="creator")renderCreator();
  else if(state.screen==="game")renderGame();
  if(state.modal)renderModal();
}

function renderHome() {
  app.innerHTML=`<main id="main" class="shell home-wrap" tabindex="-1"><section class="home-hero"><div><p class="eyebrow">原創高武俠文字 RPG</p><h1>江湖歸處</h1><p class="lead">一匹染血鏢車，把三國、八派與半載軍械暗流牽到你面前。讀線索、分頭查案、拆穿嫁禍；你的選擇會決定最後由誰執掌秩序。</p><div class="chip-list" aria-label="遊戲特色"><span class="chip">八章主線</span><span class="chip">架勢戰鬥</span><span class="chip">失敗仍推進</span><span class="chip">本地存檔</span></div></div><div class="home-actions panel panel-body"><button class="btn btn-primary" data-action="new">新遊戲</button><button class="btn" data-action="continue">繼續遊戲</button><button class="btn" data-action="room">多人房間</button><button class="btn" data-action="import">匯入存檔</button><button class="btn btn-ghost" data-action="settings">設定</button><p class="muted"><strong>存檔提醒：</strong>世界與角色保存在此瀏覽器。請定期匯出 JSON 備份。</p><input id="import-file" class="sr-only" type="file" accept="application/json"></div></section></main>`;
  bind("[data-action='new']","click",()=>startCreator());
  bind("[data-action='continue']","click",continueGame);
  bind("[data-action='room']","click",()=>openModal("room"));
  bind("[data-action='settings']","click",()=>openModal("settings"));
  bind("[data-action='import']","click",()=>document.querySelector("#import-file").click());
  bind("#import-file","change",handleImportFile);
}

function startCreator() { state.creator={stats:{...DEFAULT_STATS},identityId:IDENTITIES[0].id,selectedTalentId:null,name:"",gender:"unspecified",country:"dasheng",worldName:"風起江湖",startSkillName:IDENTITIES[0].skills[0]}; state.talentRoll=rollStartingTalents(state.content.talents,state.rng);state.talentRerolled=false;state.screen="creator";render();focusMain(); }

function renderCreator() {
  const c=state.creator; const identity=IDENTITIES.find(i=>i.id===c.identityId); const total=Object.values(c.stats).reduce((a,b)=>a+b,0);
  app.innerHTML=`<main id="main" class="shell creator-wrap" tabindex="-1"><header class="topbar"><div class="brand"><button class="btn btn-ghost" data-action="back">返回</button><h1>立下名帖</h1></div><span class="chapter-mark">創角 · 五步</span></header><form id="creator-form" class="panel panel-body form-grid" novalidate><div class="field"><label for="char-name">名字</label><input id="char-name" name="name" maxlength="18" required value="${escapeAttr(c.name)}" autocomplete="off"></div><div class="field"><label for="gender">性別</label><select id="gender" name="gender"><option value="unspecified">不明示</option><option value="male">男</option><option value="female">女</option></select></div><div class="field"><label for="world-name">世界名稱</label><input id="world-name" name="worldName" maxlength="24" value="${escapeAttr(c.worldName)}"></div><div class="field"><label for="country">起始國家</label><select id="country" name="country">${Object.entries(COUNTRIES).map(([id,v])=>`<option value="${id}" ${id===c.country?"selected":""}>${v.name}</option>`).join("")}</select></div><fieldset class="field span-all"><legend>身份</legend><div class="identity-grid">${IDENTITIES.map(item=>`<button class="btn select-card" type="button" data-identity="${item.id}" aria-pressed="${item.id===c.identityId}"><strong>${item.name} · ${item.ability}</strong><span>${item.description}</span></button>`).join("")}</div></fieldset><fieldset class="field span-all"><legend>五大屬性 <span class="number ${total===100?"success":"danger"}">${total}／100</span></legend><div class="stat-list">${Object.entries(c.stats).map(([key,value])=>`<div class="stat-row"><span>${STAT_LABELS[key]}</span><button type="button" class="btn" data-stat="${key}" data-delta="-1" aria-label="降低${STAT_LABELS[key]}">−</button><output>${value}</output><button type="button" class="btn" data-stat="${key}" data-delta="1" aria-label="提高${STAT_LABELS[key]}">＋</button></div>`).join("")}</div><p class="muted">單項最低 5、開局最高 50，合計必須為 100。</p></fieldset><fieldset class="field span-all"><legend>天賦</legend><p>第一格三選一；另兩格為命數隨機。開局可整組免費重骰一次。</p><div class="talent-grid">${state.talentRoll.choice.map(t=>`<button class="btn select-card" type="button" data-talent="${t.id}" aria-pressed="${t.id===c.selectedTalentId}"><strong>${t.name}</strong><span>${t.description}</span></button>`).join("")}</div><p>命數：${state.talentRoll.random.map(t=>`<span class="chip">${t.name} · ${t.description}</span>`).join(" ")}</p><button class="btn" type="button" data-action="reroll" ${state.talentRerolled?"disabled":""}>${state.talentRerolled?"已使用免費重骰":"重骰整組天賦"}</button></fieldset><div class="field span-all"><label for="start-skill">起始武功</label><select id="start-skill" name="startSkill">${identity.skills.map(name=>`<option ${name===c.startSkillName?"selected":""}>${name}</option>`).join("")}</select></div><div class="span-all"><p id="creator-error" class="danger" role="alert" tabindex="-1"></p><button class="btn btn-primary" type="submit">確認角色，進入江湖</button></div></form></main>`;
  document.querySelector("#gender").value=c.gender;
  bind("[data-action='back']","click",()=>{state.screen="home";render();});
  document.querySelectorAll("[data-identity]").forEach(btn=>btn.addEventListener("click",()=>{syncCreatorInputs();c.identityId=btn.dataset.identity;c.startSkillName=IDENTITIES.find(i=>i.id===c.identityId).skills[0];renderCreator();}));
  document.querySelectorAll("[data-stat]").forEach(btn=>btn.addEventListener("click",()=>{syncCreatorInputs();const key=btn.dataset.stat,delta=Number(btn.dataset.delta);const next=c.stats[key]+delta;if(next>=5&&next<=50)c.stats[key]=next;renderCreator();}));
  document.querySelectorAll("[data-talent]").forEach(btn=>btn.addEventListener("click",()=>{syncCreatorInputs();c.selectedTalentId=btn.dataset.talent;renderCreator();}));
  bind("[data-action='reroll']","click",()=>{syncCreatorInputs();state.talentRoll=rollStartingTalents(state.content.talents,state.rng);state.talentRerolled=true;c.selectedTalentId=null;renderCreator();});
  bind("#creator-form","submit",submitCreator);
}

function syncCreatorInputs(){const form=document.querySelector("#creator-form");if(!form)return;const data=new FormData(form);Object.assign(state.creator,{name:String(data.get("name")??""),gender:data.get("gender"),worldName:String(data.get("worldName")??""),country:data.get("country"),startSkillName:data.get("startSkill")});}

async function submitCreator(event){event.preventDefault();syncCreatorInputs();try{if(!state.creator.selectedTalentId)throw new Error("請從三個正面天賦中選擇一個");const chosen=state.talentRoll.choice.find(t=>t.id===state.creator.selectedTalentId);state.character=createCharacter({name:state.creator.name,gender:state.creator.gender,identityId:state.creator.identityId,stats:state.creator.stats,startSkillName:state.creator.startSkillName},[chosen,...state.talentRoll.random],state.content.skills);state.world=createWorld({name:state.creator.worldName,startingCountry:state.creator.country,ownerCharacterId:state.character.id,seed:state.rng.seed});state.character.homeWorldId=state.world.id;state.engine=new GameEngine({world:state.world,character:state.character,content:state.content});state.screen="game";await saveGame({world:state.world,character:state.character,type:"auto",index:0});render();focusMain();toast("角色與世界已建立，並完成自動存檔。");}catch(error){const alert=document.querySelector("#creator-error");alert.textContent=error.message;alert.focus();}}

function renderGame(){const battle=state.battle;if(battle){renderBattle();return;}const scene=state.engine.sceneView();const chapter=state.content.chapters.find(c=>c.chapter===state.world.chapter);app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><h1>江湖歸處</h1><span class="chapter-mark">第${state.world.chapter}章 · ${chapter?.name??"後日談"}</span></div><button class="btn btn-ghost" data-open="save">存檔</button></header><main id="main" class="game-grid" tabindex="-1"><aside class="side-column left-column">${renderStatusCard(state.character)}${renderLocationCard()}</aside><section class="main-column">${scene?renderScene(scene):renderChapterBridge(chapter)}</section><aside class="side-column right-column">${renderClues()}${renderIntentCard()}</aside></main>${renderBottomNav()}</div>`;bindGameShell();if(scene)document.querySelectorAll("[data-choice]").forEach(btn=>btn.addEventListener("click",()=>handleSceneChoice(btn.dataset.choice)));else{document.querySelectorAll("[data-chapter-choice]").forEach(btn=>btn.addEventListener("click",()=>handleChapterChoice(btn.dataset.chapterChoice)));bind("[data-action='chapter-battle']","click",startChapterBattle);}}

function renderStatusCard(character){const id=IDENTITIES.find(i=>i.id===character.identityId);return `<section class="panel panel-body status-card"><p class="eyebrow">${id?`${escapeHtml(id.name)} · ${escapeHtml(id.ability)}`:"我方戰況"}</p><h2>${escapeHtml(character.name)}</h2>${resource("氣血",character.hp,character.maxHp,"hp")}${resource("內力",character.inner,character.maxInner,"inner")}${resource("架勢",character.posture,character.maxPosture,"posture")}<p class="muted">初入江湖${character.moneyWen!=null?` · ${character.moneyWen} 文`:""}</p></section>`;}
function renderLocationCard(){return `<section class="panel panel-body status-card"><h2>洛川城</h2><p>暮雨 · 第 ${state.world.clock.day} 日</p><p class="muted">已到訪地點可在地圖中快速旅行。</p></section>`;}
function renderClues(){return `<section class="panel panel-body status-card"><h2>隊伍情報</h2>${state.world.clues.length?`<ul class="clue-list">${state.world.clues.map(id=>`<li>${escapeHtml(CLUE_LABELS[id]??id)}</li>`).join("")}</ul>`:`<p class="muted">尚無可共享情報。</p>`}</section>`;}
function renderIntentCard(){return `<section class="panel panel-body status-card"><h2>當前脈絡</h2><p>${state.world.flags.last_defeat_scene?"上次交鋒所得情報仍被保留。":"你的重大選擇會在後續章節被消費。"}</p></section>`;}
function renderScene(scene){return `<article class="paper scene"><p class="eyebrow">案卷 · ${state.world.currentSceneId}</p><h2>${escapeHtml(scene.title)}</h2><div class="scene-copy">${escapeHtml(scene.text)}</div><div class="choices">${scene.choices.map(c=>`<button class="btn choice-btn ${c.major?"major-choice":""}" data-choice="${c.id}">${escapeHtml(c.label)}${c.major?" · 重大選擇":""}</button>`).join("")}</div></article>`;}
function renderChapterBridge(chapter){if(state.world.flags.game_complete)return renderEnding();const summaries={2:"軍械帳冊指向一整條跨城利益鏈。商盟、官府與無門會都握有其中一段。",3:"三大門派因失蹤弟子與偽造軍械互相指控。證據足以止戰，也足以選邊。",4:"兩國軍械被人互換，邊境只差一支誤射的箭就會開戰。",5:"血河門殘酷的歷史是真的，被嫁禍的案件也是真的。三派正爭奪門主之位。",6:"三國高層入局，幕後集團卻並非一條心。你要決定誰有資格留下。",7:"邊境、門派、刺殺與守城同時爆發。你無法救下所有人。",8:"盟友與敵人已由前七章寫定。最後要決定的，是亂世之後的秩序。"};const battleDone=state.world.flags[`chapter_${chapter.chapter}_battle_defeated`];const enemy=selectChapterEnemy(chapter);return `<article class="paper scene"><p class="eyebrow">第 ${chapter.chapter} 章</p><h2>${escapeHtml(chapter.name)}</h2><p class="scene-copy">${escapeHtml(summaries[chapter.chapter]??"")}</p><div class="choices">${battleDone?chapter.majorChoices.map(c=>`<button class="btn choice-btn major-choice" data-chapter-choice="${c.id}">${escapeHtml(c.label)} · 重大選擇</button>`).join(""):`<p><strong>${escapeHtml(enemy.name)}</strong> 擋住了通往真相的最後一步。</p><button class="btn btn-primary" data-action="chapter-battle">迎戰${escapeHtml(enemy.name)}</button>`}</div></article>`;}
function renderEnding(){const finalChoice=state.world.flags.chapter_8_choice;const chapter=state.content.chapters[7];const label=chapter.majorChoices.find(c=>c.id===finalChoice)?.label??"未定";return `<article class="paper scene"><p class="eyebrow">後日談</p><h2>江湖歸處</h2><p class="scene-copy">你選擇了「${escapeHtml(label)}」。有人稱這是妥協，有人稱它是新局。洛川的舊案卷被封入庫中，但每一個被救下的人、每一個交惡或結盟的勢力，都記得你在亂世裡做過的決定。\n\n江湖沒有真正的結束。只有下一次，有人願意再次拔劍之前，先把真相看清。</p><div class="choices"><button class="btn btn-primary" data-action="export-ending">匯出完整江湖錄</button><button class="btn" data-action="home">返回首頁</button></div></article>`;}
function renderBottomNav(){return `<nav class="bottom-nav" aria-label="主要功能"><button class="btn" data-open="character">角色</button><button class="btn" data-open="skills">武功</button><button class="btn" data-open="map">地圖</button><button class="btn" data-open="quests">任務</button><button class="btn" data-open="menu">更多</button></nav>`;}

async function handleSceneChoice(id){try{const choice=state.engine.choose(id);if(choice.battle){startBattle(choice);return;}if(choice.complete)await saveGame({world:state.world,character:state.character,type:"auto",index:(state.world.chapter-1)%3});render();}catch(error){toast(error.message,"error");}}
function startBattle(choice){const hero=makePlayerCombatant(state.character,state.content.skills);const ally=makeNpcCompanion("陸小川",state.content.skills);const enemyDef=choice.battle.includes("boss")?state.content.enemies.find(e=>e.id==="enemy_004"):state.content.enemies.find(e=>e.id==="enemy_001");const enemy=makeEnemy(enemyDef,state.content.skills,2);state.battle=new BattleSystem({party:[hero,ally],enemies:[enemy],rng:state.rng});if(choice.battle==="boss_observed"){enemy.observed=1;state.battle.log.push("你在開戰前看出嚴震強行運功，久戰後架勢會變得鬆散。");}state.pendingBattleChoice=choice;render();}
function selectChapterEnemy(chapter){const choices=chapter.keyEnemyIds.map(id=>state.content.enemies.find(e=>e.id===id)).filter(Boolean);if(chapter.chapter===8){const paths=[1,2,3,4,5,6,7].map(n=>state.world.flags[`chapter_${n}_path`]??0);const score=paths.reduce((a,b)=>a+b,0);return choices[score%choices.length]??choices.at(-1);}return choices.find(e=>e.tier==="major_boss")??choices.find(e=>e.tier==="boss")??choices[0];}
function startChapterBattle(){const chapter=state.content.chapters.find(c=>c.chapter===state.world.chapter);const enemyDef=selectChapterEnemy(chapter);const hero=makePlayerCombatant(state.character,state.content.skills);const ally=makeNpcCompanion("陸小川",state.content.skills);const enemy=makeEnemy(enemyDef,state.content.skills,2);state.battle=new BattleSystem({party:[hero,ally],enemies:[enemy],rng:state.rng});state.pendingBattleChoice={chapterBattle:true,chapter:chapter.chapter};render();}
function renderBattle(){const snap=state.battle.snapshot();const hero=snap.party[0];const target=snap.enemies.find(e=>e.hp>0)??snap.enemies[0];app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><h1>交鋒</h1><span class="chapter-mark">第 ${snap.round} 回合</span></div><span>敵意：${escapeHtml(target.intent?.label??"不明")}</span></header><main id="main" class="game-grid" tabindex="-1"><aside class="side-column left-column">${renderStatusCard(hero)}</aside><section class="main-column"><article class="paper scene battlefield"><div class="combatants">${[...snap.party,...snap.enemies].map(renderCombatant).join("")}</div><div class="combat-log" aria-label="戰鬥紀錄">${snap.log.slice(-8).map(line=>`<div>${escapeHtml(line)}</div>`).join("")}</div>${snap.finished?`<button class="btn btn-primary" data-action="finish-battle">${snap.finished==="victory"?"收劍，繼續查案":"回城整頓"}</button>`:renderBattleActions(hero,target)}</article></section><aside class="side-column right-column"><section class="panel panel-body"><h2>敵人意圖</h2><p>${escapeHtml(target.intent?.label??"不明")}</p><p>觀察層級：${target.observed}／3</p></section></aside></main></div>`;if(snap.finished)bind("[data-action='finish-battle']","click",finishBattle);else document.querySelectorAll("[data-combat-action]").forEach(btn=>btn.addEventListener("click",()=>submitCombatAction(JSON.parse(btn.dataset.combatAction))));}
function renderCombatant(c){return `<div class="combatant ${c.vulnerableTurns?"is-broken":""}"><strong>${escapeHtml(c.name)}</strong>${c.vulnerableTurns?" <span class='danger'>破綻</span>":""}${resource("氣血",c.hp,c.maxHp,"hp")}${resource("內力",c.inner,c.maxInner,"inner")}${resource("架勢",c.posture,c.maxPosture,"posture")}</div>`;}
function renderBattleActions(hero,target){const actions=[{label:"普通攻擊",action:{type:"attack",targetId:target.id}},{label:"防禦",action:{type:"defend"}},{label:"觀察",action:{type:"observe",targetId:target.id}},{label:"護衛陸小川",action:{type:"guard",targetId:"npc_001"}},{label:`金創散（${Math.max(0,3-hero.consumablesUsed)}）`,action:{type:"item"}},...hero.skills.map(skill=>({label:`${skill.name} · ${skill.innerCost} 內力`,action:{type:"skill",skillId:skill.id,targetId:target.id}}))];return `<div class="choices">${actions.map(({label,action})=>`<button class="btn choice-btn" data-combat-action='${escapeAttr(JSON.stringify(action))}'>${escapeHtml(label)}</button>`).join("")}</div>`;}
function submitCombatAction(action){state.battle.submit(action);renderBattle();}
async function finishBattle(){const result=state.battle.finished;state.character.hp=state.character.maxHp;state.character.inner=state.character.maxInner;state.character.posture=state.character.maxPosture;if(state.pendingBattleChoice.chapterBattle){if(result==="victory")state.world.flags[`chapter_${state.pendingBattleChoice.chapter}_battle_defeated`]=true;else state.world.flags.last_defeat_scene=`chapter_${state.pendingBattleChoice.chapter}_battle`;state.world.updatedAt=new Date().toISOString();}else state.engine.finishBattle(state.pendingBattleChoice,result);state.battle=null;state.pendingBattleChoice=null;await saveGame({world:state.world,character:state.character,type:"auto",index:(state.world.chapter-1)%3});render();}
async function handleChapterChoice(id){const current=state.world.chapter;state.engine.continueChapter(id);state.character.moneyWen+=current*250;state.character.realm=Math.min(5,Math.floor(current/2));await saveGame({world:state.world,character:state.character,type:"auto",index:(state.world.chapter-1)%3});render();toast(state.world.flags.game_complete?"八章已完成，後日談已生成。":"重大選擇已寫入世界旗標，並獲得章節報酬。");}

function bindGameShell(){document.querySelectorAll("[data-open]").forEach(btn=>btn.addEventListener("click",()=>openModal(btn.dataset.open)));bind("[data-action='export-ending']","click",exportAll);bind("[data-action='home']","click",()=>{state.screen="home";render();});}
function openModal(type){state.modalTrigger=document.activeElement;state.modal=type;renderModal();}
function closeModal(){document.querySelector(".modal-backdrop")?.remove();app.inert=false;state.modal=null;state.modalTrigger?.focus?.();state.modalTrigger=null;}

async function renderModal(){document.querySelector(".modal-backdrop")?.remove();const content=await modalContent(state.modal);app.inert=true;document.body.insertAdjacentHTML("beforeend",`<div class="modal-backdrop" data-action="backdrop"><section class="modal panel" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header class="modal-head"><h2 id="modal-title">${escapeHtml(content.title)}</h2><button class="btn btn-ghost" data-action="close" aria-label="關閉">關閉</button></header><div class="modal-content">${content.body}</div></section></div>`);bind("[data-action='close']","click",closeModal);bind("[data-action='backdrop']","click",e=>{if(e.target===e.currentTarget)closeModal();});bind("[data-action='manual-save']","click",manualSave);bind("[data-action='export']","click",exportAll);bind("[data-action='import-modal']","change",handleImportFile);bind("[data-action='create-room']","click",createRoom);bind("[data-action='join-room']","click",joinRoom);bind("[data-action='open-save']","click",()=>openModal("save"));document.querySelector(".modal [data-action='close']")?.focus();}

async function modalContent(type){if(type==="character"&&state.character)return {title:"角色",body:`${renderStatusCard(state.character)}<h3>五大屬性</h3><p>${Object.entries(state.character.stats).map(([k,v])=>`${STAT_LABELS[k]} ${v}`).join("　")}</p><h3>天賦</h3><div class="chip-list">${state.character.talents.map(id=>`<span class="chip">${escapeHtml(state.content.talents.find(t=>t.id===id)?.name??id)}</span>`).join("")}</div>`};if(type==="skills"&&state.character)return {title:"武功",body:`<p>已裝備 ${state.character.equippedSkills.length}／6</p>${state.character.equippedSkills.map(id=>{const s=state.content.skills.find(x=>x.id===id);return `<section class="panel panel-body"><strong>${escapeHtml(s.name)}</strong><p>${s.type} · ${s.grade} · 氣血 ${s.power.hp}／破勢 ${s.power.posture}／內力 ${s.innerCost}</p></section>`;}).join("")}`};if(type==="map")return {title:"節點地圖",body:`<p>目前：洛川城</p><div class="chip-list">${state.content.locations.map(l=>`<span class="chip">${escapeHtml(l.name)}</span>`).join("")}</div>`};if(type==="quests")return {title:"任務與旗標",body:`${state.content.chapters.map(ch=>`<p><strong>第${ch.chapter}章 ${escapeHtml(ch.name)}</strong>　${escapeHtml(state.world?.quests[ch.mainQuestId]??(state.world?.flags[`chapter_${ch.chapter}_complete`]?"completed":"locked"))}</p>`).join("")}`};if(type==="menu")return {title:"更多",body:`<div class="choices"><button class="btn" data-action="open-save">存檔與備份</button><p>勢力：${state.content.factions.map(f=>`${f.name} ${state.world?factionLabel(state.world.factionRelations[f.id]??0):"中立"}`).join("／")}</p><p>三國通緝：大晟 ${state.world?.wantedLevels.dasheng??0}、北朔 ${state.world?.wantedLevels.beishuo??0}、南黎 ${state.world?.wantedLevels.nanli??0}</p></div>`};if(type==="save"){const slots=await listSlots();return {title:"存檔與備份",body:`<p class="muted">瀏覽器資料遭清除時，本地存檔也會消失。請定期匯出。</p><div class="choices"><button class="btn btn-primary" data-action="manual-save">手動存檔</button><button class="btn" data-action="export">匯出全部 JSON</button><label class="btn">匯入 JSON<input class="sr-only" type="file" accept="application/json" data-action="import-modal"></label></div><h3>最近存檔</h3>${slots.length?slots.map(s=>`<p>${s.slotId} · ${new Date(s.savedAt).toLocaleString("zh-TW")}</p>`).join(""):"<p>尚無存檔。</p>"}`};}if(type==="room")return {title:"多人房間",body:`<p>本機版使用瀏覽器 BroadcastChannel，可在同一裝置的多個分頁測試 1～4 人房間；正式服務可替換 RoomTransport。</p><div class="field"><label for="room-code">房間代碼</label><input id="room-code" maxlength="5" autocomplete="off"></div><div class="choices"><button class="btn btn-primary" data-action="create-room">建立房間</button><button class="btn" data-action="join-room">加入房間</button></div><div id="room-status" role="status"></div>`};return {title:"設定",body:`<div class="field"><label for="text-size">文字大小</label><select id="text-size"><option>標準</option><option>較大</option></select></div><p>系統會自動遵循「減少動態效果」偏好。所有關鍵資訊同時提供文字與數值。</p>`};}

async function manualSave(){if(!state.world)return toast("尚未建立世界");await saveGame({world:state.world,character:state.character,type:"manual",index:0});toast("已寫入手動存檔。");openModal("save");}
async function continueGame(){try{const slot=localStorage.getItem("jianghu:lastSlot")??"auto_0";const snap=await loadSlot(slot);state.world=snap.world;state.character=snap.character;state.engine=new GameEngine({world:state.world,character:state.character,content:state.content});state.screen="game";render();}catch(error){toast(`無法繼續：${error.message}`);}}
async function exportAll(){const saves=await getAllSaves();if(state.world&&!saves.worlds.some(w=>w.id===state.world.id)){saves.worlds.push(state.world);saves.characters.push(state.character);}const bundle=await createExportBundle({...saves,settings:{textSize:localStorage.getItem("jianghu:textSize")??"standard"}});downloadJson(bundle,`jianghu-${new Date().toISOString().slice(0,10)}.json`);toast("已匯出完整江湖錄。");}
async function handleImportFile(event){const file=event.target.files?.[0];if(!file)return;try{const parsed=await parseImport(await file.text());if(!confirm(`將匯入 ${parsed.summary.worlds} 個世界、${parsed.summary.characters} 名角色。是否繼續？`))return;await importSaves(parsed.bundle);toast("存檔已通過校驗並匯入。");closeModal();}catch(error){toast(`匯入失敗：${error.message}`);}}
async function createRoom(){const transport=new LocalRoomTransport();state.room=new RoomController({transport,isHost:true,playerId:state.character?.id??`player_${Date.now()}`});const room=await state.room.create({worldId:state.world?.id??"new_world",chapter:state.world?.chapter??1});document.querySelector("#room-code").value=room.roomId;document.querySelector("#room-status").textContent=`房間 ${room.roomId} 已建立。請在另一分頁輸入代碼加入。`;}
async function joinRoom(){const code=document.querySelector("#room-code").value.trim();if(!code)return;const transport=new LocalRoomTransport();state.room=new RoomController({transport,isHost:false,playerId:state.character?.id??`guest_${Date.now()}`});await state.room.join(code);document.querySelector("#room-status").textContent=`已送出加入房間 ${code.toUpperCase()} 的請求。`;}

function resource(label,value,max,type){const pct=max?Math.round(value/max*100):0;return `<div class="resource"><div class="stat-row"><span>${label}</span><span class="number">${Math.round(value)}／${Math.round(max)}</span></div><div class="meter ${type}" role="meter" aria-label="${label}" aria-valuemin="0" aria-valuemax="${max}" aria-valuenow="${value}"><span style="width:${Math.max(0,Math.min(100,pct))}%"></span></div></div>`;}
function bind(selector,event,handler){document.querySelector(selector)?.addEventListener(event,handler);}
function focusMain(){requestAnimationFrame(()=>document.querySelector("#main")?.focus());}
function toast(message,type="success"){const region=document.querySelector("#toast-region");const item=document.createElement("div");item.className=`toast ${type==="error"?"danger":""}`;item.textContent=message;region.append(item);setTimeout(()=>item.remove(),5000);}
function escapeHtml(value=""){return String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]));}
function escapeAttr(value=""){return escapeHtml(value).replace(/`/g,"&#96;");}

window.addEventListener("keydown",event=>{if(event.key==="Escape"&&state.modal)closeModal();});
