import { createFinalScenario } from "./systems/zhaoye-final-battle.js";
import { scaleStoryEncounter } from "./core/zhaoye-callbacks.js";
import { calculateRealm } from "./systems/realm-system.js";
import { packBattle, restoreBattle } from "./persistence/battle-snapshot.js";
import { createZhaoyeState, evidenceSummary } from "./core/zhaoye-engine.js";
import { useStoryCatalog } from "./core/zhaoye-catalog.js";
import { REALMS } from "./config/constants.js";
import { loadContent } from "./data/loader.js";
import { COUNTRIES, DEFAULT_STATS, IDENTITIES, STAT_LABELS, SKILL_REALMS } from "./config/constants.js";
import { SeededRng } from "./core/rng.js";
import { GameEngine, createWorld } from "./core/game-engine.js";
import { CLUE_LABELS } from "./core/story.js";
import { addProficiency, createCharacter, rollStartingTalents } from "./systems/progression-system.js";
import { BattleSystem, makeEnemy, makeNpcCompanion, makePlayerCombatant } from "./systems/battle-system.js";
import { factionLabel } from "./systems/faction-system.js";
import { saveGame, loadSlot, getAllSaves, importSaves, listSlots, clearAllSaves } from "./persistence/save-service.js";
import { createExportBundle, downloadJson, parseImport } from "./persistence/import-export.js";
import { LocalRoomTransport } from "./multiplayer/local-transport.js";
import { RoomController } from "./multiplayer/room-controller.js";
import { addItem, equipItem, recalculateEquipment, removeItem, useConsumable } from "./systems/inventory-system.js";
import { equipSkill, innerLoad, learnInnerArt, learnSkill, toggleInnerArt, unequipSkill, upgradeMeridian } from "./systems/training-system.js";
import { advanceClock, availableDestinations, travel } from "./systems/travel-system.js";
import { canRecruit, dismissNpc, recruitNpc } from "./systems/npc-system.js";
import { applyTalentModifiers } from "./systems/talent-system.js";
import { buyEquipment, buyItem, priceAt, restAtInn, sellItem, shopStock } from "./systems/economy-system.js";
import { OFFICE_RANKS, availableOfficeTasks, completeOfficeTask, joinOffice, resignOffice } from "./systems/office-system.js";

const app = document.querySelector("#app");
const state = { screen:"boot", content:null, character:null, world:null, engine:null, rng:new SeededRng(`jianghu-${Date.now()}`), battle:null, battleSkillUses:{}, pendingBattleChoice:null, modal:null, modalTrigger:null, talentRoll:null, talentRerolled:false, creator:{ stats:{...DEFAULT_STATS}, identityId:IDENTITIES[0].id, selectedTalentId:null }, room:null, roomUnsubscribe:null };

boot();

if ("serviceWorker" in navigator && location.protocol !== "file:") window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));

async function boot() {
  try { state.content=await loadContent();applySettings(); state.screen="home"; render(); }
  catch(error){app.innerHTML=`<main class="boot-screen"><p class="eyebrow">內容驗證失敗</p><h1>案卷無法展開</h1><p class="danger">${escapeHtml(error.message)}</p></main>`;console.error(error);}
}

function render() {
  if(state.screen==="home")renderHome();
  else if(state.screen==="creator")renderCreator();
  else if(state.screen==="game")renderGame();
  if(state.modal)renderModal();
}

function renderHome() {
  app.innerHTML=`<main id="main" class="shell home-wrap" tabindex="-1"><section class="home-hero"><div><p class="eyebrow">原創高武俠文字 RPG</p><h1>照夜行</h1><p class="lead">一封鴉渡舊約，牽出三國私運與失蹤者。逐項查證、救人、履約；讓被留在門外的人，也看得見那盞燈。</p><div class="chip-list" aria-label="遊戲特色"><span class="chip">八章主線</span><span class="chip">架勢戰鬥</span><span class="chip">失敗仍推進</span><span class="chip">本地存檔</span></div></div><div class="home-actions panel panel-body"><button class="btn btn-primary" data-action="new">新遊戲</button><button class="btn" data-action="continue">繼續遊戲</button><button class="btn" data-action="room">多人房間</button><button class="btn" data-action="import">匯入存檔</button><button class="btn btn-ghost" data-action="settings">設定</button><p class="muted"><strong>存檔提醒：</strong>世界與角色保存在此瀏覽器。請定期匯出 JSON 備份。</p><input id="import-file" class="sr-only" type="file" accept="application/json"></div></section></main>`;
  bind("[data-action='new']","click",()=>startCreator());
  bind("[data-action='continue']","click",continueGame);
  bind("[data-action='room']","click",()=>openModal("room"));
  bind("[data-action='settings']","click",()=>openModal("settings"));
  bind("[data-action='import']","click",()=>document.querySelector("#import-file").click());
  bind("#import-file","change",handleImportFile);
}

function startCreator() { state.creator={stats:{...DEFAULT_STATS},identityId:IDENTITIES[0].id,selectedTalentId:null,name:"",gender:"unspecified",country:"dasheng",worldName:"風起江湖",startSkillName:IDENTITIES[0].skills[0]}; state.talentRoll=rollStartingTalents(state.content.talents,state.rng);state.talentRerolled=false;state.screen="creator";render();focusMain(); }

function renderCreator() {
  const c=state.creator; const identity=IDENTITIES.find(i=>i.id===c.identityId); const total=Object.values(c.stats).reduce((a,b)=>a+b,0);
  app.innerHTML=`<main id="main" class="shell creator-wrap" tabindex="-1"><header class="topbar"><div class="brand"><button class="btn btn-ghost" data-action="back">返回</button><h1>立下名帖</h1></div><span class="chapter-mark">創角 · 五步</span></header><form id="creator-form" class="panel panel-body form-grid" novalidate><div class="field"><label for="char-name">名字</label><input id="char-name" name="name" maxlength="18" required value="${escapeAttr(c.name)}" autocomplete="off"></div><div class="field"><label for="gender">性別</label><select id="gender" name="gender"><option value="unspecified">不明示</option><option value="male">男</option><option value="female">女</option></select></div><div class="field"><label for="world-name">世界名稱</label><input id="world-name" name="worldName" maxlength="24" value="${escapeAttr(c.worldName)}"></div><div class="field"><label for="country">起始國家</label><select id="country" name="country">${Object.entries(COUNTRIES).map(([id,v])=>`<option value="${id}" ${id===c.country?"selected":""}>${v.name}</option>`).join("")}</select></div><fieldset class="field span-all"><legend>身份</legend><div class="identity-grid">${IDENTITIES.map(item=>`<button class="btn select-card" type="button" data-identity="${item.id}" aria-pressed="${item.id===c.identityId}"><strong>${item.name} · ${item.ability}</strong><span>${item.description}</span></button>`).join("")}</div></fieldset><fieldset class="field span-all"><legend>五大屬性 <span class="number ${total===100?"success":"danger"}">${total}／100</span></legend><div class="stat-list">${Object.entries(c.stats).map(([key,value])=>`<div class="stat-row"><span>${STAT_LABELS[key]}</span><button type="button" class="btn" data-stat="${key}" data-delta="-1" aria-label="降低${STAT_LABELS[key]}">−</button><output>${value}</output><button type="button" class="btn" data-stat="${key}" data-delta="1" aria-label="提高${STAT_LABELS[key]}">＋</button></div>`).join("")}</div><p class="muted">單項最低 5、開局最高 50，合計必須為 100。</p></fieldset><fieldset class="field span-all"><legend>天賦</legend><p>第一格三選一；另兩格為命數隨機。開局可整組免費重骰一次。</p><div class="talent-grid">${state.talentRoll.choice.map(t=>`<button class="btn select-card" type="button" data-talent="${t.id}" aria-pressed="${t.id===c.selectedTalentId}"><strong>${t.name}</strong><span>${t.description}</span></button>`).join("")}</div><p>命數：${state.talentRoll.random.map(t=>`<span class="chip">${t.name} · ${t.description}</span>`).join(" ")}</p><button class="btn" type="button" data-action="reroll" ${state.talentRerolled?"disabled":""}>${state.talentRerolled?"已使用免費重骰":"重骰整組天賦"}</button></fieldset><div class="field span-all"><label for="start-skill">起始武功</label><select id="start-skill" name="startSkill">${identity.skills.map(name=>`<option ${name===c.startSkillName?"selected":""}>${name}</option>`).join("")}</select></div><div class="span-all"><p id="creator-error" class="danger" role="alert" tabindex="-1"></p><button class="btn btn-primary" type="submit">確認角色，進入江湖</button></div></form></main>`;
  document.querySelector("#gender").value=c.gender;
  bind("[data-action='back']","click",()=>{state.screen="home";render();});
  document.querySelectorAll("[data-identity]").forEach(btn=>btn.addEventListener("click",()=>{syncCreatorInputs();c.identityId=btn.dataset.identity;c.startSkillName=IDENTITIES.find(i=>i.id===c.identityId).skills[0];renderCreator();}));
  document.querySelectorAll("[data-stat]").forEach(btn=>btn.addEventListener("click",()=>{syncCreatorInputs();const key=btn.dataset.stat,delta=Number(btn.dataset.delta);const next=c.stats[key]+delta;if(next>=5&&next<=50)c.stats[key]=next;renderCreator();}));
  document.querySelectorAll("[data-talent]").forEach(btn=>btn.addEventListener("click",()=>{syncCreatorInputs();c.selectedTalentId=btn.dataset.talent;renderCreator();}));
  bind("[data-action='reroll']","click",()=>{syncCreatorInputs();state.talentRoll=rollStartingTalents(state.content.talents,state.rng);state.talentRerolled=true;c.selectedTalentId=null;renderCreator();});
  bind("#creator-form","submit",submitCreator);
}

function syncCreatorInputs(){const form=document.querySelector("#creator-form");if(!form)return;const data=new FormData(form);Object.assign(state.creator,{name:String(data.get("name")??""),gender:data.get("gender"),worldName:String(data.get("worldName")??""),country:data.get("country"),startSkillName:data.get("startSkill")});}

async function submitCreator(event){event.preventDefault();syncCreatorInputs();try{if(!state.creator.selectedTalentId)throw new Error("請從三個正面天賦中選擇一個");const chosen=state.talentRoll.choice.find(t=>t.id===state.creator.selectedTalentId);state.character=createCharacter({name:state.creator.name,gender:state.creator.gender,identityId:state.creator.identityId,stats:state.creator.stats,startSkillName:state.creator.startSkillName},[chosen,...state.talentRoll.random],state.content.skills);recalculateEquipment(state.character,state.content.equipment,state.content.meridians);state.world=createWorld({name:state.creator.worldName,startingCountry:state.creator.country,ownerCharacterId:state.character.id,seed:state.rng.seed});state.world.zhaoye=createZhaoyeState();state.world.currentSceneId="1-0";state.world.currentLocationId=({dasheng:"location_005",beishuo:"location_007",nanli:"location_012"})[state.world.startingCountry];state.world.visitedLocations=[state.world.currentLocationId];useStoryCatalog(state.content,true);state.character.homeWorldId=state.world.id;state.engine=new GameEngine({world:state.world,character:state.character,content:state.content});state.screen="game";await saveGame({world:state.world,character:state.character,type:"auto",index:0});render();focusMain();toast("角色與世界已建立，並完成自動存檔。");}catch(error){const alert=document.querySelector("#creator-error");alert.textContent=error.message;alert.focus();}}

function renderGame(){const battle=state.battle;if(battle){renderBattle();return;}const scene=state.engine.sceneView();const chapter=state.content.chapters.find(c=>c.chapter===state.world.chapter);app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><h1>${state.world.zhaoye?"照夜行":"江湖歸處（舊版）"}</h1><span class="chapter-mark">第${state.world.chapter}章 · ${chapter?.name??"後日談"}</span></div><button class="btn btn-ghost" data-open="save">存檔</button></header><main id="main" class="game-grid" tabindex="-1"><aside class="side-column left-column">${renderStatusCard(state.character)}${renderLocationCard()}</aside><section class="main-column">${scene?renderScene(scene):renderChapterBridge(chapter)}</section><aside class="side-column right-column">${renderClues()}${renderIntentCard()}</aside></main>${renderBottomNav()}</div>`;bindGameShell();if(scene)document.querySelectorAll("[data-choice]").forEach(btn=>btn.addEventListener("click",()=>handleSceneChoice(btn.dataset.choice)));else{document.querySelectorAll("[data-chapter-choice]").forEach(btn=>btn.addEventListener("click",()=>handleChapterChoice(btn.dataset.chapterChoice)));bind("[data-action='chapter-battle']","click",startChapterBattle);}}

function renderStatusCard(character){const id=IDENTITIES.find(i=>i.id===character.identityId);return `<section class="panel panel-body status-card"><p class="eyebrow">${id?`${escapeHtml(id.name)} · ${escapeHtml(id.ability)}`:"我方戰況"}</p><h2>${escapeHtml(character.name)}</h2>${resource("氣血",character.hp,character.maxHp,"hp")}${resource("內力",character.inner,character.maxInner,"inner")}${resource("架勢",character.posture,character.maxPosture,"posture")}<p class="muted">${REALMS[character.realm??0]}${character.moneyWen!=null?` · ${character.moneyWen} 文`:""}</p></section>`;}
function renderLocationCard(){const location=state.content.locations.find(item=>item.id===state.world.currentLocationId);return `<section class="panel panel-body status-card"><h2>${escapeHtml(location?.name??"洛川城")}</h2><p>${escapeHtml(segmentLabel(state.world.clock.segment))} · 第 ${state.world.clock.day} 日</p><p class="muted">已到訪地點可在地圖中快速旅行。</p></section>`;}
function renderClues(){if(state.world.zhaoye)return `<section class="panel panel-body status-card"><h2>已知證據與支援</h2><p class="scene-copy">${escapeHtml(evidenceSummary(state.world))}</p></section>`;return `<section class="panel panel-body status-card"><h2>隊伍情報</h2>${state.world.clues.length?`<ul class="clue-list">${state.world.clues.map(id=>`<li>${escapeHtml(CLUE_LABELS[id]??id)}</li>`).join("")}</ul>`:`<p class="muted">尚無可共享情報。</p>`}</section>`;}
function renderIntentCard(){return `<section class="panel panel-body status-card"><h2>當前脈絡</h2><p>${state.world.flags.last_defeat_scene?"上次交鋒所得情報仍被保留。":"你的重大選擇會在後續章節被消費。"}</p></section>`;}
function renderScene(scene){return `<article class="paper scene"><p class="eyebrow">案卷 · ${state.world.currentSceneId}</p><h2>${escapeHtml(scene.title)}</h2><div class="scene-copy">${escapeHtml(scene.text)}</div><div class="choices">${scene.choices.map(c=>`<button class="btn choice-btn ${c.major?"major-choice":""}" data-choice="${escapeAttr(c.id)}" ${c.disabled?"disabled":""}>${escapeHtml(c.label)}${c.major?" · 重大選擇":""}</button>`).join("")}${state.world.zhaoye?.chapterSafe&&state.world.flags.game_complete?`<button class="btn" data-action="export-ending">匯出完整照夜行案卷</button><button class="btn" data-action="home">返回首頁</button>`:""}</div></article>`;}
function renderChapterBridge(chapter){if(state.world.flags.game_complete)return renderEnding();const summaries={2:"軍械帳冊指向一整條跨城利益鏈。商盟、官府與無門會都握有其中一段。",3:"三大門派因失蹤弟子與偽造軍械互相指控。證據足以止戰，也足以選邊。",4:"兩國軍械被人互換，邊境只差一支誤射的箭就會開戰。",5:"血河門殘酷的歷史是真的，被嫁禍的案件也是真的。三派正爭奪門主之位。",6:"三國高層入局，幕後集團卻並非一條心。你要決定誰有資格留下。",7:"邊境、門派、刺殺與守城同時爆發。你無法救下所有人。",8:"盟友與敵人已由前七章寫定。最後要決定的，是亂世之後的秩序。"};const battleDone=state.world.flags[`chapter_${chapter.chapter}_battle_defeated`];const enemy=selectChapterEnemy(chapter);return `<article class="paper scene"><p class="eyebrow">第 ${chapter.chapter} 章</p><h2>${escapeHtml(chapter.name)}</h2><p class="scene-copy">${escapeHtml(summaries[chapter.chapter]??"")}</p><div class="choices">${battleDone?chapter.majorChoices.map(c=>`<button class="btn choice-btn major-choice" data-chapter-choice="${c.id}">${escapeHtml(c.label)} · 重大選擇</button>`).join(""):`<p><strong>${escapeHtml(enemy.name)}</strong> 擋住了通往真相的最後一步。</p><button class="btn btn-primary" data-action="chapter-battle">迎戰${escapeHtml(enemy.name)}</button>`}</div></article>`;}
function renderEnding(){const finalChoice=state.world.flags.chapter_8_choice;const chapter=state.content.chapters[7];const label=chapter.majorChoices.find(c=>c.id===finalChoice)?.label??"未定";const chapterRecord=state.content.chapters.slice(0,7).map(item=>{const choice=item.majorChoices.find(option=>option.id===state.world.flags[`chapter_${item.chapter}_choice`]);return choice?`第 ${item.chapter} 章「${item.name}」：${choice.label}`:null;}).filter(Boolean);const allies=state.content.factions.filter(faction=>(state.world.factionRelations[faction.id]??0)>=11).map(faction=>faction.name);const enemies=state.content.factions.filter(faction=>(state.world.factionRelations[faction.id]??0)<=-11).map(faction=>faction.name);const companions=state.world.party.npcIds.map(id=>state.content.npcs.find(npc=>npc.id===id)?.name).filter(Boolean);const wanted=Object.entries(state.world.wantedLevels).filter(([,level])=>level>0).map(([country,level])=>`${COUNTRIES[country]?.name??country} ${level} 星`);const office=state.world.officeState?`你以${COUNTRIES[state.world.officeState.country]?.name??state.world.officeState.country}${OFFICE_RANKS[state.world.officeState.rankIndex]}的身分參與重建；官勳 ${state.world.officeState.merit} 成為日後問責的案卷。`:"你沒有接受任何一國官印，保留了不受朝堂節制的江湖身分。";return `<article class="paper scene"><p class="eyebrow">動態後日談</p><h2>江湖歸處</h2><div class="scene-copy"><p>你最終選擇了「${escapeHtml(label)}」。這不是沒有代價的答案，而是你願意公開承擔的秩序。</p><p>${escapeHtml(allies.length?`${allies.join("、")}履行舊約，成為新局的支柱。`:"沒有勢力完全站到你身後，新秩序只能從地方盟約慢慢長成。")}</p><p>${escapeHtml(enemies.length?`${enemies.join("、")}拒絕承認結果，江湖仍留有下一場衝突的火種。`:"昔日敵手暫時收劍，但每一方都在觀察新秩序是否守諾。")}</p><p>${escapeHtml(companions.length?`${companions.join("、")}陪你走到最後，各自帶著共同經歷返回自己的道路。`:"最後一程由你獨自走完，沿途留下的名字仍被案卷記住。")}</p><p>${escapeHtml(wanted.length?`你仍背負通緝：${wanted.join("、")}；有些國境從此不能光明正大踏入。`:"三國通緝皆已平息，你可以用真名穿過每一道城門。")}</p><p>${escapeHtml(office)}</p><h3>八章留痕</h3><ul>${chapterRecord.map(text=>`<li>${escapeHtml(text)}</li>`).join("")}<li>第 8 章「江湖歸處」：${escapeHtml(label)}</li></ul><p>江湖沒有真正的結束。只有下一次，有人願意再次拔劍之前，先把真相看清。</p></div><div class="choices"><button class="btn btn-primary" data-action="export-ending">匯出完整江湖錄</button><button class="btn" data-action="home">返回首頁</button></div></article>`;}
function renderBottomNav(){return `<nav class="bottom-nav" aria-label="主要功能"><button class="btn" data-open="character">角色</button><button class="btn" data-open="skills">武功</button><button class="btn" data-open="map">地圖</button><button class="btn" data-open="quests">任務</button><button class="btn" data-open="menu">更多</button></nav>`;}

let sceneChoiceBusy=false;
async function handleSceneChoice(id){if(sceneChoiceBusy)return;sceneChoiceBusy=true;try{const completedChapter=state.world.chapter;const choice=state.engine.choose(id);if(choice.battle){await startBattle(choice);return;}if(choice.complete)grantChapterRewards(completedChapter);await saveGame({world:state.world,character:state.character,type:"auto",index:(completedChapter-1)%3});render();focusMain();}catch(error){toast(error.message,"error");}finally{sceneChoiceBusy=false;}}
async function startBattle(choice){const party=makeCurrentParty();const chapter=state.content.chapters.find(item=>item.chapter===state.world.chapter);const enemyDef=state.world.chapter===1?((choice.battle.includes("boss")||choice.eventId==="1-3")?state.content.enemies.find(e=>e.id==="enemy_004"):state.content.enemies.find(e=>e.id==="enemy_001")):selectChapterEnemy(chapter);const encounterDef=choice.sparring||choice.shortEncounter?{...enemyDef,tier:"elite",stats:{strength:20,constitution:18,agility:20,comprehension:20,willpower:20},phases:[],skillIds:enemyDef.skillIds.slice(0,1)}:enemyDef;const enemy=makeEnemy(choice.enemyName?{...encounterDef,name:choice.enemyName}:encounterDef,state.content.skills,party.length);state.battle=new BattleSystem({party,enemies:[enemy],rng:state.rng,scenario:state.world.zhaoye&&choice.eventId==="8-4"?createFinalScenario(state.engine.battleProgress()?.done):null});state.battleSkillUses={};if(choice.battle==="boss_observed"){enemy.observed=1;state.battle.log.push("你在開戰前看出嚴震強行運功，久戰後架勢會變得鬆散。");}if(state.world.zhaoye){const reasons=scaleStoryEncounter(enemy,state.world,party.length);enemy.observeInfo=["他正守著撤離通道，場景操作與攻擊各占一次行動。","可看敵意預告安排防守，必要機關不限制身份或招式。","重要人物只能非致命制伏；救援進度另行結算。"];state.battle.log.push(...reasons);}state.battle.onScenarioAction=round=>state.engine.battleAction?.("objective",round);state.pendingBattleChoice=choice;await persistActiveBattle();render();focusMain();}
function selectChapterEnemy(chapter){const choices=chapter.keyEnemyIds.map(id=>state.content.enemies.find(e=>e.id===id)).filter(Boolean);if(chapter.chapter===8&&!state.world.zhaoye){const paths=[1,2,3,4,5,6,7].map(n=>state.world.flags[`chapter_${n}_path`]??0);const score=paths.reduce((a,b)=>a+b,0);return choices[score%choices.length]??choices.at(-1);}return choices.find(e=>e.tier==="major_boss")??choices.find(e=>e.tier==="boss")??choices[0];}
function startChapterBattle(){const chapter=state.content.chapters.find(c=>c.chapter===state.world.chapter);const enemyDef=selectChapterEnemy(chapter);const party=makeCurrentParty();const enemy=makeEnemy(enemyDef,state.content.skills,party.length);state.battle=new BattleSystem({party,enemies:[enemy],rng:state.rng});state.battleSkillUses={};state.pendingBattleChoice={chapterBattle:true,chapter:chapter.chapter};render();}
function makeCurrentParty(){return [makePlayerCombatant(state.character,state.content.skills),...state.world.party.npcIds.map(id=>state.content.npcs.find(npc=>npc.id===id)).filter(Boolean).map(npc=>makeNpcCompanion(npc,state.content.skills,state.world.chapter))];}
function renderBattle(){const snap=state.battle.snapshot();const hero=snap.party.find(actor=>actor.hp>0)??snap.party[0];const target=snap.enemies.find(e=>e.hp>0)??snap.enemies[0];app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><h1>交鋒</h1><span class="chapter-mark">第 ${snap.round} 回合</span></div><span>敵意：${escapeHtml(target.intent?.label??"不明")}</span></header><main id="main" class="game-grid" tabindex="-1"><aside class="side-column left-column">${renderStatusCard(hero)}</aside><section class="main-column"><article class="paper scene battlefield"><div class="combatants">${[...snap.party,...snap.enemies].map(renderCombatant).join("")}</div><div class="combat-log" aria-label="戰鬥紀錄">${snap.log.slice(-8).map(line=>`<div>${escapeHtml(line)}</div>`).join("")}</div>${snap.finished?`<button class="btn btn-primary" data-action="finish-battle">${snap.finished==="victory"?"收劍，繼續查案":"回城整頓"}</button>`:renderBattleActions(hero,target)}</article></section><aside class="side-column right-column"><section class="panel panel-body"><h2>敵人意圖</h2><p>${escapeHtml(target.intent?.label??"不明")}</p><p>觀察層級：${target.observed}／3</p></section></aside></main></div>`;if(snap.finished)bind("[data-action='finish-battle']","click",finishBattle);else document.querySelectorAll("[data-combat-action]").forEach(btn=>btn.addEventListener("click",()=>submitCombatAction(JSON.parse(btn.dataset.combatAction))));}
function renderCombatant(c){return `<div class="combatant ${c.vulnerableTurns?"is-broken":""}"><strong>${escapeHtml(c.name)}</strong>${c.vulnerableTurns?" <span class='danger'>破綻</span>":""}${resource("氣血",c.hp,c.maxHp,"hp")}${resource("內力",c.inner,c.maxInner,"inner")}${resource("架勢",c.posture,c.maxPosture,"posture")}</div>`;}
function renderBattleActions(hero,target){const stock=state.character.inventory.find(entry=>entry.itemId==="item_001")?.quantity??0;const usesLeft=Math.max(0,3-hero.consumablesUsed);const ally=state.battle.party.find(actor=>actor.id!==hero.id&&actor.hp>0);const objective=state.engine.battleProgress?.();const actions=[...(objective&&objective.done<objective.objectives.length?[{label:`場景行動：${objective.objectives[objective.done]}（${objective.done}／${objective.objectives.length}${Number.isFinite(objective.limit)?`；期限 ${objective.limit} 回合`:""}）`,action:{type:"objective"},disabled:state.battle.round>objective.limit}]:[]),{label:"普通攻擊",action:{type:"attack",targetId:target.id}},{label:"防禦",action:{type:"defend"}},{label:"觀察",action:{type:"observe",targetId:target.id}},{label:ally?`護衛${ally.name}`:"護衛（無目標）",action:{type:"guard",targetId:ally?.id},disabled:!ally},{label:`金創散（背包 ${stock}／本戰可用 ${usesLeft}）`,action:{type:"item"},disabled:stock===0||usesLeft===0},...hero.skills.map(skill=>({label:`${skill.name} · ${skill.innerCost} 內力`,action:{type:"skill",skillId:skill.id,targetId:target.id}}))];return `<div class="choices">${actions.map(({label,action,disabled})=>`<button class="btn choice-btn" data-combat-action='${escapeAttr(JSON.stringify(action))}' ${disabled?"disabled":""}>${escapeHtml(label)}</button>`).join("")}</div>`;}
let combatBusy=false;
async function persistActiveBattle(){if(!state.world.zhaoye||!state.battle)return;state.world.zhaoye.activeBattle=packBattle(state.battle,state.pendingBattleChoice,state.battleSkillUses);await saveGame({world:state.world,character:state.character,type:"auto",index:(state.world.chapter-1)%3});}
function restoreActiveBattle(){state.battle=null;state.pendingBattleChoice=null;const saved=state.world.zhaoye?.activeBattle;if(!saved)return;const restored=restoreBattle(saved);state.battle=restored.battle;if(restored.choice?.eventId==="8-4"&&!state.battle.scenario){state.battle.scenario=createFinalScenario(state.engine.battleProgress()?.done);for(const enemy of state.battle.enemies)enemy.phases=[];if(!state.battle.finished)state.battle.prepareIntents();}state.rng=state.battle.rng;state.pendingBattleChoice=restored.choice;state.battleSkillUses=restored.skillUses;state.battle.onScenarioAction=round=>state.engine.battleAction?.("objective",round);}
async function submitCombatAction(action){if(combatBusy)return;combatBusy=true;try{if(action.type==="item"){try{removeItem(state.character,"item_001",1);}catch(error){toast(error.message,"error");return;}}if(action.type==="skill"){const hero=state.battle.party.find(actor=>actor.id===state.character.id);const skill=hero?.skills.find(item=>item.id===action.skillId);if(skill&&hero.inner>=skill.innerCost){const uses=(state.battleSkillUses[action.skillId]??0)+1;state.battleSkillUses[action.skillId]=uses;addProficiency(state.character,action.skillId,12*(1+(state.character.proficiencyPct??0)),uses);}}state.battle.submit(action);if(!state.battle.finished&&state.pendingBattleChoice.maxRounds&&state.battle.round>state.pendingBattleChoice.maxRounds){const hero=state.battle.living("party")[0],foe=state.battle.living("enemy")[0];state.battle.finished=hero&&foe&&(hero.hp/hero.maxHp+hero.posture/hero.maxPosture>=foe.hp/foe.maxHp+foe.posture/foe.maxPosture)?"victory":"defeat";state.battle.log.push("約定回合已到，短戰結算；無論勝負都可繼續查案。");}await persistActiveBattle();renderBattle();}catch(error){toast(`戰鬥存檔失敗：${error.message}`,"error");renderBattle();}finally{combatBusy=false;}}
function refreshStoryRealm(){if(state.world?.zhaoye){state.character.realm=calculateRealm(state.character).realm;recalculateEquipment(state.character,state.content.equipment,state.content.meridians);}}
async function finishBattle(){refreshStoryRealm();const result=state.battle.finished;state.character.hp=state.character.maxHp;state.character.inner=state.character.maxInner;state.character.posture=state.character.maxPosture;if(state.pendingBattleChoice.chapterBattle){if(result==="victory")state.world.flags[`chapter_${state.pendingBattleChoice.chapter}_battle_defeated`]=true;else state.world.flags.last_defeat_scene=`chapter_${state.pendingBattleChoice.chapter}_battle`;state.world.updatedAt=new Date().toISOString();}else state.engine.finishBattle(state.pendingBattleChoice,result);state.battle=null;state.pendingBattleChoice=null;if(state.world.zhaoye)delete state.world.zhaoye.activeBattle;await saveGame({world:state.world,character:state.character,type:"auto",index:(state.world.chapter-1)%3});render();}
async function handleChapterChoice(id){const current=state.world.chapter;state.engine.continueChapter(id);grantChapterRewards(current);await saveGame({world:state.world,character:state.character,type:"auto",index:(state.world.chapter-1)%3});render();toast(state.world.flags.game_complete?"八章已完成，後日談已生成。":"重大選擇已寫入世界旗標，並獲得金錢、修為與固定裝備。");}
function grantChapterRewards(chapter){state.character.moneyWen+=chapter*250;state.character.cultivation=(state.character.cultivation??0)+chapter*100;const rewardIds=["equipment_121","equipment_196","equipment_241","equipment_101","equipment_201","equipment_230","equipment_280","equipment_120"];const equipmentId=rewardIds[chapter-1];if(equipmentId&&!state.character.ownedEquipment.includes(equipmentId))state.character.ownedEquipment.push(equipmentId);const healing=state.content.items.find(item=>item.id==="item_001");const stock=state.character.inventory.find(entry=>entry.itemId===healing.id);const space=healing.stackLimit-(stock?.quantity??0);if(space>0&&(stock||state.character.inventory.length<30))addItem(state.character,healing.id,Math.min(2,space),state.content.items);if(!state.world.zhaoye)state.character.realm=Math.min(5,Math.floor(chapter/2));}

function bindGameShell(){document.querySelectorAll("[data-open]").forEach(btn=>btn.addEventListener("click",()=>openModal(btn.dataset.open)));bind("[data-action='export-ending']","click",exportAll);bind("[data-action='home']","click",()=>{state.screen="home";render();});}
function openModal(type){state.modalTrigger=document.activeElement;state.modal=type;renderModal();}
function closeModal(){document.querySelector(".modal-backdrop")?.remove();app.inert=false;state.modal=null;state.modalTrigger?.focus?.();state.modalTrigger=null;}

async function renderModal(){
  document.querySelector(".modal-backdrop")?.remove();const content=await modalContent(state.modal);app.inert=true;
  document.body.insertAdjacentHTML("beforeend",`<div class="modal-backdrop" data-action="backdrop"><section class="modal panel" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header class="modal-head"><h2 id="modal-title">${escapeHtml(content.title)}</h2><button class="btn btn-ghost" data-action="close" aria-label="關閉">關閉</button></header><div class="modal-content">${content.body}</div></section></div>`);
  bind("[data-action='close']","click",closeModal);bind("[data-action='backdrop']","click",e=>{if(e.target===e.currentTarget)closeModal();});bind("[data-action='export']","click",exportAll);bind("[data-action='import-modal']","change",handleImportFile);bind("[data-action='clear-saves']","click",clearSavesFromUi);bind("[data-action='create-room']","click",createRoom);bind("[data-action='join-room']","click",joinRoom);bind("[data-action='room-ready']","click",toggleRoomReady);bind("[data-action='room-start']","click",startRoom);bind("[data-action='room-chat']","click",sendRoomChat);bind("[data-action='open-save']","click",()=>openModal("save"));
  bind("[data-action='room-reunite']","click",()=>roomCommand("reunite"));bind("[data-action='room-vote-start']","click",startRoomVote);bind("[data-action='room-vote-resolve']","click",()=>roomCommand("vote-resolve"));bind("[data-action='room-battle-open']","click",openRoomBattle);bind("[data-action='room-battle-resolve']","click",()=>roomCommand("battle-resolve"));
  document.querySelectorAll("[data-room-split]").forEach(button=>button.addEventListener("click",()=>roomCommand("split",{lineId:button.dataset.roomSplit})));
  document.querySelectorAll("[data-room-vote]").forEach(button=>button.addEventListener("click",()=>roomCommand("vote",{choiceId:button.dataset.roomVote})));
  document.querySelectorAll("[data-room-tie]").forEach(button=>button.addEventListener("click",()=>roomCommand("vote-resolve",{hostTieChoice:button.dataset.roomTie})));
  document.querySelectorAll("[data-room-battle-action]").forEach(button=>button.addEventListener("click",()=>roomCommand("battle-action",{action:button.dataset.roomBattleAction})));
  document.querySelectorAll("[data-manual-slot]").forEach(button=>button.addEventListener("click",()=>manualSave(Number(button.dataset.manualSlot))));
  document.querySelectorAll("[data-load-slot]").forEach(button=>button.addEventListener("click",()=>loadFromSlot(button.dataset.loadSlot)));
  bind("#text-size","change",event=>{localStorage.setItem("jianghu:textSize",event.target.value);applySettings();});
  document.querySelectorAll("[data-section]").forEach(button=>button.addEventListener("click",()=>openModal(button.dataset.section)));
  document.querySelectorAll("[data-equip]").forEach(button=>button.addEventListener("click",()=>handleEquip(button.dataset.equip)));
  document.querySelectorAll("[data-learn-skill]").forEach(button=>button.addEventListener("click",()=>handleLearnSkill(button.dataset.learnSkill)));
  document.querySelectorAll("[data-toggle-skill]").forEach(button=>button.addEventListener("click",()=>handleToggleSkill(button.dataset.toggleSkill)));
  document.querySelectorAll("[data-travel]").forEach(button=>button.addEventListener("click",()=>handleTravel(button.dataset.travel,false)));
  document.querySelectorAll("[data-fast-travel]").forEach(button=>button.addEventListener("click",()=>handleTravel(button.dataset.fastTravel,true)));
  document.querySelectorAll("[data-learn-inner]").forEach(button=>button.addEventListener("click",()=>handleLearnInner(button.dataset.learnInner)));document.querySelectorAll("[data-toggle-inner]").forEach(button=>button.addEventListener("click",()=>handleToggleInner(button.dataset.toggleInner)));
  document.querySelectorAll("[data-meridian]").forEach(button=>button.addEventListener("click",()=>handleMeridian(button.dataset.meridian)));
  document.querySelectorAll("[data-recruit]").forEach(button=>button.addEventListener("click",()=>handleRecruit(button.dataset.recruit)));
  document.querySelectorAll("[data-dismiss-npc]").forEach(button=>button.addEventListener("click",()=>handleDismiss(button.dataset.dismissNpc)));
  document.querySelectorAll("[data-buy-item]").forEach(button=>button.addEventListener("click",()=>handleBuyItem(button.dataset.buyItem)));
  document.querySelectorAll("[data-sell-item]").forEach(button=>button.addEventListener("click",()=>handleSellItem(button.dataset.sellItem)));
  document.querySelectorAll("[data-use-item]").forEach(button=>button.addEventListener("click",()=>handleUseItem(button.dataset.useItem)));
  document.querySelectorAll("[data-buy-equipment]").forEach(button=>button.addEventListener("click",()=>handleBuyEquipment(button.dataset.buyEquipment)));
  bind("[data-action='rest-inn']","click",handleRestAtInn);bind("[data-action='join-office']","click",handleJoinOffice);bind("[data-action='resign-office']","click",handleResignOffice);
  document.querySelectorAll("[data-office-task]").forEach(button=>button.addEventListener("click",()=>handleOfficeTask(button.dataset.officeTask)));
  document.querySelector(".modal [data-action='close']")?.focus();
}

async function modalContent(type){
  if(type==="character"&&state.character)return {title:"角色與裝備",body:characterModalBody()};
  if(type==="skills"&&state.character)return {title:"武功",body:skillsModalBody()};
  if(type==="map")return {title:"節點地圖",body:mapModalBody()};
  if(type==="training")return {title:"修煉",body:trainingModalBody()};
  if(type==="inventory")return {title:"背包",body:inventoryModalBody()};
  if(type==="npcs")return {title:"同行者",body:npcModalBody()};
  if(type==="shop")return {title:"城市商店與客棧",body:shopModalBody()};
  if(type==="office")return {title:"官職與官府任務",body:officeModalBody()};
  if(type==="quests")return {title:"任務與旗標",body:`${state.content.chapters.map(ch=>`<p><strong>第${ch.chapter}章 ${escapeHtml(ch.name)}</strong>　${escapeHtml(state.world?.quests[ch.mainQuestId]??(state.world?.flags[`chapter_${ch.chapter}_complete`]?"completed":"locked"))}</p>`).join("")}`};
  if(type==="menu")return {title:"更多",body:`<div class="choices"><button class="btn" data-section="training">內功與經脈</button><button class="btn" data-section="inventory">背包</button><button class="btn" data-section="npcs">同行者</button><button class="btn" data-section="shop">商店與客棧</button><button class="btn" data-section="office">官職與官府任務</button><button class="btn" data-action="open-save">存檔與備份</button><p>勢力：${state.content.factions.map(f=>`${f.name} ${state.world?factionLabel(state.world.factionRelations[f.id]??0):"中立"}`).join("／")}</p><p>三國通緝：大晟 ${state.world?.wantedLevels.dasheng??0}、北朔 ${state.world?.wantedLevels.beishuo??0}、南黎 ${state.world?.wantedLevels.nanli??0}</p></div>`};
  if(type==="save"){const slots=await listSlots();const byId=new Map(slots.map(slot=>[slot.slotId,slot]));const slotCard=(type,index)=>{const id=`${type}_${index}`;const slot=byId.get(id);return `<section class="panel panel-body"><strong>${type==="auto"?"自動":"手動"} ${index+1}</strong><p>${slot?new Date(slot.savedAt).toLocaleString("zh-TW"):"空槽"}</p><div class="choices">${type==="manual"?`<button class="btn" data-manual-slot="${index}">${slot?"覆寫":"存入"}</button>`:""}${slot?`<button class="btn" data-load-slot="${id}">載入</button>`:""}</div></section>`;};return {title:"存檔與備份",body:`<p class="muted">瀏覽器資料遭清除時，本地存檔也會消失。請定期匯出。</p><div class="choices"><button class="btn" data-action="export">匯出全部 JSON</button><label class="btn">匯入 JSON<input class="sr-only" type="file" accept="application/json" data-action="import-modal"></label><button class="btn" data-action="clear-saves">清空本機存檔</button></div><h3>3 個自動槽</h3>${Array.from({length:3},(_,index)=>slotCard("auto",index)).join("")}<h3>5 個手動槽</h3>${Array.from({length:5},(_,index)=>slotCard("manual",index)).join("")}`};}
  if(type==="room")return {title:"多人房間",body:roomModalBody()};
  const textSize=localStorage.getItem("jianghu:textSize")??"standard";return {title:"設定",body:`<div class="field"><label for="text-size">文字大小</label><select id="text-size"><option value="standard" ${textSize==="standard"?"selected":""}>標準</option><option value="large" ${textSize==="large"?"selected":""}>較大</option></select></div><p>系統會自動遵循「減少動態效果」偏好。所有關鍵資訊同時提供文字與數值。</p>`};
}

function characterModalBody(){const slots={weapon:"武器",armor:"衣甲",bracer:"護腕",accessory:"飾品"};return `${renderStatusCard(state.character)}<h3>五大屬性</h3><p>${Object.entries(state.character.stats).map(([key,value])=>`${STAT_LABELS[key]} ${value}`).join("　")}</p><h3>裝備</h3>${Object.entries(slots).map(([slot,label])=>{const equippedId=state.character.equipment[slot];const equipped=state.content.equipment.find(item=>item.id===equippedId);const owned=state.character.ownedEquipment.map(id=>state.content.equipment.find(item=>item.id===id)).filter(item=>item?.slot===slot);return `<section class="panel panel-body"><strong>${label}：${escapeHtml(equipped?.name??"未裝備")}</strong><div class="chip-list">${owned.map(item=>`<button class="btn" data-equip="${item.id}" ${item.id===equippedId?"disabled":""}>裝備${escapeHtml(item.name)}</button>`).join("")||"<span class='muted'>尚未取得</span>"}</div></section>`;}).join("")}<h3>天賦</h3><div class="chip-list">${state.character.talents.map(id=>`<span class="chip">${escapeHtml(state.content.talents.find(t=>t.id===id)?.name??id)}</span>`).join("")}</div>`;}
function skillsModalBody(){const learned=Object.entries(state.character.skills).map(([id,mastery])=>({skill:state.content.skills.find(item=>item.id===id),mastery})).filter(entry=>entry.skill);const available=state.content.skills.filter(skill=>!state.character.skills[skill.id]).slice(0,8);const costs={basic:100,normal:200,advanced:400,ultimate:800};return `<p>六格配招：${state.character.equippedSkills.length}／6　修為：${state.character.cultivation??0}</p><h3>已學武功</h3>${learned.map(({skill,mastery})=>{const equipped=state.character.equippedSkills.includes(skill.id);return `<section class="panel panel-body"><strong>${escapeHtml(skill.name)} · ${SKILL_REALMS[mastery.realm]}</strong><p>${escapeHtml(skill.type)}／${escapeHtml(skill.grade)}　熟練 ${mastery.proficiency}／100　完整度 ${Math.round(mastery.completeness*100)}%</p><p>每階傷害與破勢 +5%，內力消耗 −3%。</p><button class="btn" data-toggle-skill="${skill.id}">${equipped?"卸下配招":"裝入配招"}</button></section>`;}).join("")}<h3>可研習秘籍</h3>${available.map(skill=>`<section class="panel panel-body"><strong>${escapeHtml(skill.name)}</strong><p>${escapeHtml(skill.grade)} · 需 ${costs[skill.grade]} 修為</p><button class="btn" data-learn-skill="${skill.id}">研習</button></section>`).join("")}`;}

function mapModalBody(){const current=state.content.locations.find(item=>item.id===state.world.currentLocationId);const destinations=availableDestinations(state.world,state.content.locations);const fastCities=state.world.visitedLocations.map(id=>state.content.locations.find(item=>item.id===id)).filter(location=>location?.type==="city"&&location.id!==state.world.currentLocationId);return `<p>目前：<strong>${escapeHtml(current?.name??"未知")}</strong>　${segmentLabel(state.world.clock.segment)}，第 ${state.world.clock.day} 日</p><h3>相鄰路線</h3><div class="choices">${destinations.map(location=>`<button class="btn" data-travel="${location.id}">前往${escapeHtml(location.name)} · 可能觸發旅行事件</button>`).join("")||"<p>目前沒有可行路線。</p>"}</div><h3>已到訪城市快速旅行</h3><div class="choices">${fastCities.map(location=>`<button class="btn" data-fast-travel="${location.id}">驛站前往${escapeHtml(location.name)} · 80 文</button>`).join("")||"<p class='muted'>尚無其他已到訪城市。</p>"}</div><h3>已到訪</h3><div class="chip-list">${state.world.visitedLocations.map(id=>`<span class="chip">${escapeHtml(state.content.locations.find(item=>item.id===id)?.name??id)}</span>`).join("")}</div>`;}

function trainingModalBody(){const learned=Object.entries(state.character.innerArts);const load=innerLoad(state.character);const available=state.content.innerArts.filter(art=>!state.character.innerArts[art.id]).slice(0,6);const costs={basic:100,normal:250,advanced:500,ultimate:900};return `<p>修為：<strong>${state.character.cultivation??0}</strong>　運行內功 ${load.count} 套，自然回氣 ${(state.character.innerRegenRate??load.regenRate)*100}%／回合</p><h3>已學內功</h3>${learned.length?learned.map(([id,stateValue])=>{const art=state.content.innerArts.find(item=>item.id===id);return `<section class="panel panel-body"><strong>${escapeHtml(art?.name??id)} · ${SKILL_REALMS[stateValue.realm??0]}</strong><p>最大內力 +${art?.maxInner??0}　${escapeHtml(art?.description??"")}</p><button class="btn" data-toggle-inner="${id}">${stateValue.active?"停止運行":"運行內功"}</button></section>`;}).join(""):`<p class="muted">尚未學會內功。</p>`}<h3>可研讀內功</h3>${available.map(art=>`<section class="panel panel-body"><strong>${escapeHtml(art.name)}</strong><p>${escapeHtml(art.description)} · 需 ${costs[art.grade]} 修為</p><button class="btn" data-learn-inner="${art.id}">研讀</button></section>`).join("")}<h3>經脈</h3><div class="choices">${state.content.meridians.map(meridian=>{const level=state.character.meridians[meridian.id]??0;const cost=level<10?meridian.costs[level]:null;return `<button class="btn" data-meridian="${meridian.id}" ${level>=10?"disabled":""}>${escapeHtml(meridian.name)} Lv.${level} ${cost!=null?`· 需 ${cost} 修為`:"· 已滿"}</button>`;}).join("")}</div>`;}

function inventoryModalBody(){return `<p>一般背包 ${state.character.inventory.length}／30 格；劇情道具另計。</p>${state.character.inventory.length?state.character.inventory.map(entry=>{const item=state.content.items.find(row=>row.id===entry.itemId);return `<section class="panel panel-body"><strong>${escapeHtml(item?.name??entry.itemId)} × ${entry.quantity}</strong><p>${escapeHtml(item?.description??"")}</p></section>`;}).join(""):`<p class="muted">背包是空的。</p>`}<h3>固定裝備收藏</h3><div class="chip-list">${state.character.ownedEquipment.map(id=>`<span class="chip">${escapeHtml(state.content.equipment.find(item=>item.id===id)?.name??id)}</span>`).join("")}</div>`;}

function shopModalBody(){const location=state.content.locations.find(item=>item.id===state.world.currentLocationId);if(!location?.facilities?.some(id=>["shop","medicine","inn"].includes(id)))return `<p>此地沒有可用商店或客棧。前往城市後再來。</p>`;const stock=shopStock(location,state.world.chapter,state.content.items,state.content.equipment);const usableEffects=new Set(["heal_flat","restore_inner_flat","restore_posture_flat","cultivation"]);return `<p><strong>${escapeHtml(location.name)}</strong>　現銀 ${state.character.moneyWen} 文　地區價格 ×${location.priceModifier??1}</p>${location.facilities.includes("inn")?`<button class="btn" data-action="rest-inn">住店休整 · ${Math.round(60*(location.priceModifier??1))} 文</button>`:""}<h3>藥鋪與雜貨</h3>${stock.items.map(item=>`<section class="panel panel-body"><strong>${escapeHtml(item.name)}</strong><p>${escapeHtml(item.description)} · ${priceAt(item,location)} 文</p><button class="btn" data-buy-item="${item.id}">購買 1 個</button></section>`).join("")||"<p class='muted'>今日無貨。</p>"}<h3>鐵匠鋪</h3>${stock.equipment.map(item=>`<section class="panel panel-body"><strong>${escapeHtml(item.name)} · ${escapeHtml(item.rarity)}</strong><p>${Object.entries(item.stats).map(([key,value])=>`${key} +${value}`).join("　")} · ${priceAt(item,location)} 文</p><button class="btn" data-buy-equipment="${item.id}" ${state.character.ownedEquipment.includes(item.id)?"disabled":""}>${state.character.ownedEquipment.includes(item.id)?"已持有":"購買"}</button></section>`).join("")||"<p class='muted'>今日無裝備可售。</p>"}<h3>出售與使用背包物品</h3>${state.character.inventory.map(entry=>{const item=state.content.items.find(row=>row.id===entry.itemId);return `<section class="panel panel-body"><strong>${escapeHtml(item?.name??entry.itemId)} × ${entry.quantity}</strong><p>出售價 ${item?priceAt(item,location,{selling:true}):0} 文</p><button class="btn" data-sell-item="${entry.itemId}">出售 1 個</button>${item?.effects?.some(effect=>usableEffects.has(effect.effectId))?`<button class="btn" data-use-item="${entry.itemId}">使用 1 個</button>`:""}</section>`;}).join("")||"<p class='muted'>沒有可出售物品。</p>"}`;}

function officeModalBody(){const location=state.content.locations.find(item=>item.id===state.world.currentLocationId);if(!location?.facilities?.includes("government"))return `<p>此地沒有官署。請前往設有官府的城市。</p>`;if(!state.world.officeState)return `<p>${escapeHtml(location.name)}官署正在招募見習役。正式效忠後一次只能任職一國；辭官會降低巡武司關係並提高原國通緝。</p><button class="btn btn-primary" data-action="join-office">效忠${escapeHtml(COUNTRIES[location.country]?.name??location.country)}官府</button>`;const office=state.world.officeState;const tasks=availableOfficeTasks(state.world,location);return `<p>效忠：<strong>${escapeHtml(COUNTRIES[office.country]?.name??office.country)}</strong>　官職：<strong>${OFFICE_RANKS[office.rankIndex]}</strong>　官勳：${office.merit}</p><p class="muted">高階官職需同時達到官勳與主線章節門檻。</p><h3>今日官府任務</h3>${tasks.map(task=>`<section class="panel panel-body"><strong>${escapeHtml(task.name)} · +${task.merit} 官勳</strong><p>${escapeHtml(task.description)}</p><button class="btn" data-office-task="${task.id}">執行任務</button></section>`).join("")||"<p class='muted'>今日可執行任務已完成，明日再來。</p>"}<button class="btn btn-ghost" data-action="resign-office">辭去官職</button>`;}

function roomModalBody(){
  const room=state.room?.state;
  if(!room)return `<p>本機版使用瀏覽器 BroadcastChannel，可在同一裝置的多個分頁測試 1～4 人；房主負責權威結算。</p><div class="field"><label for="room-code">房間代碼</label><input id="room-code" maxlength="5" autocomplete="off"></div><div class="choices"><button class="btn btn-primary" data-action="create-room">建立房間</button><button class="btn" data-action="join-room">加入房間</button></div><div id="room-status" role="status"></div>`;
  const me=room.players[state.room.playerId];const players=Object.values(room.players);const slots=Array.from({length:4},(_,index)=>{const player=players[index];return `<section class="panel panel-body"><strong>槽位 ${index+1}</strong>　${player?`${escapeHtml(player.name)}${player.id===room.hostPlayerId?" · 房主":""} · ${player.connected?(player.ready?"已準備":"未準備"):"重連等待"}`:"空位"}</section>`;}).join("");
  const chat=room.chat.length?room.chat.map(entry=>`<p><strong>${escapeHtml(room.players[entry.playerId]?.name??entry.playerId)}</strong>：${escapeHtml(entry.text)}</p>`).join(""):`<p class="muted">尚無隊伍訊息。</p>`;
  const lines=Object.entries(room.actionLines).map(([id,members])=>`<p>${id==="together"?"集合":"行動線 "+escapeHtml(id)}：${members.map(member=>escapeHtml(room.players[member]?.name??member)).join("、")||"無"}</p>`).join("");
  return `<p><strong>${escapeHtml(room.worldSummary.worldName)}</strong> · ${COUNTRIES[room.worldSummary.country]?.name??room.worldSummary.country} · 第 ${room.worldSummary.chapter} 章</p><p>房間代碼：<strong>${room.roomId}</strong>　狀態：${room.status}</p>${slots}${room.status==="lobby"?`<div class="choices"><button class="btn btn-primary" data-action="room-ready">${me?.ready?"取消準備":"準備"}</button>${state.room.isHost?`<button class="btn" data-action="room-start">開始遊戲</button>`:""}</div>`:"<p class='success'>隊伍已出發；斷線玩家可在一分鐘內重連。</p>"}<h3>隊伍聊天</h3><div class="field"><label for="room-chat">訊息</label><input id="room-chat" maxlength="300"></div><button class="btn" data-action="room-chat">傳送</button><div aria-live="polite">${chat}</div><h3>行動線</h3>${lines}${room.status==="playing"?roomPlayControls(room,me):""}`;
}

function roomPlayControls(room,me){const chapter=state.content.chapters.find(item=>item.chapter===room.worldSummary.chapter);const choiceLabel=id=>chapter?.majorChoices.find(choice=>choice.id===id)?.label??id;let vote="";if(room.vote){const counts=Object.fromEntries(room.vote.choices.map(choice=>[choice,Object.values(room.vote.ballots).filter(value=>value===choice).length]));const max=Math.max(...Object.values(counts));const leaders=room.vote.choices.filter(choice=>counts[choice]===max);vote=`<h3>重大投票</h3>${room.vote.notice?`<p role="status">${escapeHtml(room.vote.notice)}</p>`:""}<p>${room.vote.status==="open"?"投票中":"已結算"} · 尚未投票 ${room.vote.eligiblePlayerIds.filter(id=>!room.vote.ballots[id]).length} 人 · 第 ${room.vote.round??1} 輪 · 結算前可改票；全員到票後須過半，首次平票重投，再平票由房主裁決</p>${room.vote.choices.map(choice=>`<button class="btn" data-room-vote="${choice}" ${room.vote.status!=="open"||!me.connected||room.status==="paused"?"disabled":""}>${escapeHtml(choiceLabel(choice))} · ${counts[choice]} 票${room.vote.ballots[state.room.playerId]===choice?"（目前選擇）":""}</button>`).join("")}${state.room.isHost&&room.vote.status==="open"?(room.vote.round??1)>1&&leaders.length>1&&room.vote.eligiblePlayerIds.every(id=>room.vote.ballots[id])&&room.vote.eligiblePlayerIds.every(id=>room.players[id]?.connected)?`<p>平票，請房主選擇：</p>${leaders.map(choice=>`<button class="btn" data-room-tie="${choice}">${escapeHtml(choiceLabel(choice))}</button>`).join("")}`:`<button class="btn" data-action="room-vote-resolve">結算投票</button>`:""}${room.vote.status==="resolved"?`<p class="success">結果：${escapeHtml(choiceLabel(room.vote.result))}</p>`:""}`;}else if(state.room.isHost)vote=`<button class="btn" data-action="room-vote-start">發起本章重大投票</button>`;
  const battle=room.battle;let battleUi="";if(battle){const submitted=Boolean(battle.submissions[state.room.playerId]);battleUi=`<h3>同步戰鬥 · 第 ${battle.round} 回合</h3><p>${escapeHtml(battle.enemyName)}：${battle.enemyHp}／${battle.maxEnemyHp}　我方：${battle.partyHp[state.room.playerId]??0}／100</p><div class="choices">${["attack","skill","defend","observe"].map(action=>`<button class="btn" data-room-battle-action="${action}" ${submitted||battle.status!=="active"?"disabled":""}>${({attack:"攻擊",skill:"武功",defend:"防禦",observe:"觀察"})[action]}</button>`).join("")}${state.room.isHost&&battle.status==="active"?`<button class="btn btn-primary" data-action="room-battle-resolve">房主結算本回合</button>`:""}</div><p>${battle.log.slice(-2).map(escapeHtml).join("<br>")}</p>${battle.status!=="active"?`<p class="success">${battle.status==="victory"?"戰鬥勝利":"隊伍撤退，情報保留"}</p>`:""}`;}else if(state.room.isHost)battleUi=`<button class="btn" data-action="room-battle-open">開始本章同步戰鬥</button>`;
  return `<div class="choices"><button class="btn" data-room-split="magistrate">前往官府線</button><button class="btn" data-room-split="escort">前往鏢盟線</button><button class="btn" data-action="room-reunite">重新集合</button></div>${vote}${battleUi}`;}

function npcModalBody(){const party=new Set(state.world.party.npcIds);const available=state.content.npcs.filter(npc=>party.has(npc.id)||canRecruit(npc,state.world)).slice(0,12);return `<p>隊伍 ${state.world.party.playerIds.length+state.world.party.npcIds.length}／4 個單位</p>${available.map(npc=>`<section class="panel panel-body"><strong>${escapeHtml(npc.name)} · ${escapeHtml(npc.role)}</strong><p>${escapeHtml(npc.introduction)}</p>${party.has(npc.id)?(npc.id==="npc_001"?"<span class='chip'>固定同行</span>":`<button class="btn" data-dismiss-npc="${npc.id}">暫離隊伍</button>`):`<button class="btn" data-recruit="${npc.id}">邀請同行</button>`}</section>`).join("")}`;}

async function persistAndRefresh(modal,message){refreshStoryRealm();await saveGame({world:state.world,character:state.character,type:"auto",index:(state.world.chapter-1)%3});toast(message);renderGame();state.modal=modal;await renderModal();}
async function handleEquip(id){try{equipItem(state.character,id,state.content.equipment);await persistAndRefresh("character","裝備已更換，衍生數值已重新計算。");}catch(error){toast(error.message,"error");}}
async function handleLearnSkill(id){try{const skill=state.content.skills.find(item=>item.id===id);if(!skill)throw new Error("武功不存在");const cost=({basic:100,normal:200,advanced:400,ultimate:800})[skill.grade];if((state.character.cultivation??0)<cost)throw new Error(`修為不足，需 ${cost}`);state.character.cultivation-=cost;learnSkill(state.character,id);await persistAndRefresh("skills",`已學會${skill.name}。`);}catch(error){toast(error.message,"error");}}
async function handleToggleSkill(id){try{if(state.character.equippedSkills.includes(id))unequipSkill(state.character,id);else equipSkill(state.character,id);await persistAndRefresh("skills","六格配招已更新。");}catch(error){toast(error.message,"error");}}
async function handleTravel(id,fast=false){try{state.world.partyMoney=state.character.moneyWen;const result=travel(state.world,id,state.content.locations,state.rng,{fast,identityId:state.character.identityId});state.character.moneyWen=state.world.partyMoney;const message=[fast?`已支付 ${result.cost} 文抵達目的地。`:result.event?`途中遭遇：${result.event}`:"已抵達目的地。",result.identityMessage].filter(Boolean).join(" ");await persistAndRefresh("map",message);}catch(error){toast(error.message,"error");}}
async function handleLearnInner(id){try{const art=state.content.innerArts.find(item=>item.id===id);if(!art)throw new Error("內功不存在");const cost=({basic:100,normal:250,advanced:500,ultimate:900})[art.grade];if((state.character.cultivation??0)<cost)throw new Error(`修為不足，需 ${cost}`);state.character.cultivation-=cost;learnInnerArt(state.character,art);recalculateEquipment(state.character,state.content.equipment,state.content.meridians);await persistAndRefresh("training",`已學會${art.name}。需主動運行才會生效。`);}catch(error){toast(error.message,"error");}}
async function handleToggleInner(id){try{toggleInnerArt(state.character,id,!state.character.innerArts[id].active);recalculateEquipment(state.character,state.content.equipment,state.content.meridians);await persistAndRefresh("training","內功運行狀態已更新。");}catch(error){toast(error.message,"error");}}
async function handleMeridian(id){try{upgradeMeridian(state.character,id);recalculateEquipment(state.character,state.content.equipment,state.content.meridians);await persistAndRefresh("training","經脈提升完成，修為已扣除。");}catch(error){toast(error.message,"error");}}
async function handleRecruit(id){try{recruitNpc(state.world,state.content.npcs.find(npc=>npc.id===id));await persistAndRefresh("npcs","同行者已加入隊伍。");}catch(error){toast(error.message,"error");}}
async function handleDismiss(id){dismissNpc(state.world,id);await persistAndRefresh("npcs","同行者已暫離隊伍。");}
async function handleBuyItem(id){try{const paid=buyItem(state.character,id,1,state.content.items,currentLocation());await persistAndRefresh("shop",`已購買道具，支付 ${paid} 文。`);}catch(error){toast(error.message,"error");}}
async function handleSellItem(id){try{const received=sellItem(state.character,id,1,state.content.items,currentLocation());await persistAndRefresh("shop",`已出售道具，取得 ${received} 文。`);}catch(error){toast(error.message,"error");}}
async function handleUseItem(id){try{const item=state.content.items.find(row=>row.id===id);useConsumable(state.character,id,state.content.items);await persistAndRefresh("shop",`已使用${item?.name??"道具"}。`);}catch(error){toast(error.message,"error");}}
async function handleBuyEquipment(id){try{const paid=buyEquipment(state.character,id,state.content.equipment,currentLocation());await persistAndRefresh("shop",`固定裝備已收入收藏，支付 ${paid} 文。`);}catch(error){toast(error.message,"error");}}
async function handleRestAtInn(){try{const paid=restAtInn(state.character,state.world,currentLocation());await persistAndRefresh("shop",`住店休整完成，支付 ${paid} 文。`);}catch(error){toast(error.message,"error");}}
async function handleJoinOffice(){try{const location=currentLocation();joinOffice(state.world,state.character,location.country);await persistAndRefresh("office",`已成為${COUNTRIES[location.country]?.name??location.country}見習役。`);}catch(error){toast(error.message,"error");}}
async function handleOfficeTask(id){try{const result=completeOfficeTask(state.world,state.character,id,currentLocation());advanceClock(state.world,1);await persistAndRefresh("office",`${result.task.name}完成；現為${result.rank}。`);}catch(error){toast(error.message,"error");}}
async function handleResignOffice(){if(!confirm("辭官會降低巡武司關係並提高原效忠國通緝，確定辭官？"))return;try{resignOffice(state.world,state.character);await persistAndRefresh("office","已辭去官職；原國官府開始留意你的行蹤。");}catch(error){toast(error.message,"error");}}
function currentLocation(){return state.content.locations.find(item=>item.id===state.world.currentLocationId);}

function normalizeLoadedState(){refreshStoryRealm();useStoryCatalog(state.content,!!state.world.zhaoye);state.character.ownedEquipment??=["equipment_001"];state.character.cultivation??=0;state.character.meridians??=Object.fromEntries(state.content.meridians.map(item=>[item.id,0]));state.character.innerArts??={};state.world.currentLocationId??=state.world.visitedLocations?.at(-1)??"location_002";state.world.partyMoney??=state.character.moneyWen??0;if(state.world.officeState){state.world.officeState.completedTasks??=[];state.character.office={country:state.world.officeState.country,rank:OFFICE_RANKS[state.world.officeState.rankIndex??0],merit:state.world.officeState.merit??0};}if(state.world.currentSceneId==="chapter_bridge")state.world.currentSceneId=`ch${state.world.chapter}_opening`;applyTalentModifiers(state.character);recalculateEquipment(state.character,state.content.equipment,state.content.meridians);}

async function manualSave(index){if(!state.world)return toast("尚未建立世界");await saveGame({world:state.world,character:state.character,type:"manual",index});toast(`已寫入手動存檔 ${index+1}。`);state.modal="save";await renderModal();}
async function loadFromSlot(slotId){try{const snap=await loadSlot(slotId);state.world=snap.world;state.character=snap.character;normalizeLoadedState();state.engine=new GameEngine({world:state.world,character:state.character,content:state.content});restoreActiveBattle();state.screen="game";closeModal();render();toast(`已載入 ${slotId}。`);}catch(error){toast(`載入失敗：${error.message}`,"error");}}
async function clearSavesFromUi(){if(!confirm("這會刪除本瀏覽器中的所有世界、角色與存檔槽；未匯出的資料無法復原。確定繼續？"))return;await clearAllSaves();state.world=null;state.character=null;state.engine=null;state.screen="home";closeModal();render();toast("本機存檔已清空。");}
async function continueGame(){try{const slot=localStorage.getItem("jianghu:lastSlot")??"auto_0";const snap=await loadSlot(slot);state.world=snap.world;state.character=snap.character;normalizeLoadedState();state.engine=new GameEngine({world:state.world,character:state.character,content:state.content});restoreActiveBattle();state.screen="game";render();}catch(error){toast(`無法繼續：${error.message}`);}}
async function exportAll(){const saves=await getAllSaves();if(state.world&&!saves.worlds.some(w=>w.id===state.world.id)){saves.worlds.push(state.world);saves.characters.push(state.character);}const bundle=await createExportBundle({...saves,settings:{textSize:localStorage.getItem("jianghu:textSize")??"standard"}});downloadJson(bundle,`jianghu-${new Date().toISOString().slice(0,10)}.json`);toast("已匯出完整江湖錄。");}
async function handleImportFile(event){const file=event.target.files?.[0];if(!file)return;try{const parsed=await parseImport(await file.text());if(!confirm(`將匯入 ${parsed.summary.worlds} 個世界、${parsed.summary.characters} 名角色。是否繼續？`))return;const result=await importSaves(parsed.bundle);if(parsed.bundle.settings?.textSize)localStorage.setItem("jianghu:textSize",parsed.bundle.settings.textSize);applySettings();toast(`存檔已通過校驗並匯入，建立 ${result.restoredSlots} 個可載入槽位。`);closeModal();}catch(error){toast(`匯入失敗：${error.message}`);}}
async function createRoom(){const transport=new LocalRoomTransport();setRoomController(new RoomController({transport,isHost:true,playerId:state.character?.id??`player_${Date.now()}`}));await state.room.create({worldId:state.world?.id??"new_world",worldName:state.world?.name??"新江湖",country:state.world?.startingCountry??"dasheng",chapter:state.world?.chapter??1,profile:{name:state.character?.name??"房主",characterId:state.character?.id??null}});await renderModal();}
async function joinRoom(){const code=document.querySelector("#room-code").value.trim().toUpperCase();if(!code)return;const transport=new LocalRoomTransport();setRoomController(new RoomController({transport,isHost:false,playerId:state.character?.id??`guest_${Date.now()}`}));await state.room.join(code,{name:state.character?.name??"訪客",characterId:state.character?.id??null});if(!state.room.state)document.querySelector("#room-status").textContent=`已送出加入房間 ${code} 的請求；若代碼有效，大廳會自動出現。`;else await renderModal();}
function setRoomController(controller){state.roomUnsubscribe?.();state.room=controller;state.roomUnsubscribe=controller.subscribe(()=>{if(state.modal==="room")renderModal();});}
async function toggleRoomReady(){try{const me=state.room.state.players[state.room.playerId];await state.room.command("ready",{ready:!me.ready});}catch(error){toast(error.message,"error");}}
async function startRoom(){try{await state.room.command("start");toast("所有玩家已準備，房主已開始遊戲。");}catch(error){toast(error.message,"error");}}
async function sendRoomChat(){const input=document.querySelector("#room-chat");try{await state.room.command("chat",{text:input.value});}catch(error){toast(error.message,"error");}}
async function roomCommand(type,payload={}){try{await state.room.command(type,payload);}catch(error){toast(error.message,"error");}}
async function startRoomVote(){const chapter=state.content.chapters.find(item=>item.chapter===state.room.state.worldSummary.chapter);await roomCommand("vote-start",{id:`chapter_${chapter.chapter}_major`,choices:chapter.majorChoices.map(choice=>choice.id),flagKey:`chapter_${chapter.chapter}_room_choice`});}
async function openRoomBattle(){const chapter=state.content.chapters.find(item=>item.chapter===state.room.state.worldSummary.chapter);const enemy=selectChapterEnemy(chapter);await roomCommand("battle-open",{id:`chapter_${chapter.chapter}_room_battle`,enemyName:enemy.name,enemyHp:100+chapter.chapter*20});}

function resource(label,value,max,type){const pct=max?Math.round(value/max*100):0;return `<div class="resource"><div class="stat-row"><span>${label}</span><span class="number">${Math.round(value)}／${Math.round(max)}</span></div><div class="meter ${type}" role="meter" aria-label="${label}" aria-valuemin="0" aria-valuemax="${max}" aria-valuenow="${value}"><span style="width:${Math.max(0,Math.min(100,pct))}%"></span></div></div>`;}
function segmentLabel(segment){return ({morning:"清晨",noon:"正午",evening:"暮色",night:"夜間"})[segment]??segment;}
function applySettings(){document.documentElement.dataset.textSize=localStorage.getItem("jianghu:textSize")??"standard";}
function bind(selector,event,handler){document.querySelector(selector)?.addEventListener(event,handler);}
function focusMain(){requestAnimationFrame(()=>document.querySelector("#main")?.focus());}
function toast(message,type="success"){const region=document.querySelector("#toast-region");const item=document.createElement("div");item.className=`toast ${type==="error"?"danger":""}`;item.textContent=message;region.append(item);setTimeout(()=>item.remove(),5000);}
function escapeHtml(value=""){return String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]));}
function escapeAttr(value=""){return escapeHtml(value).replace(/`/g,"&#96;");}

window.addEventListener("keydown",event=>{if(event.key==="Escape"&&state.modal)closeModal();});
